getpelican/pelican-plugins

liquid_tags/youtube.py

Updated the youtube url to get the embedded player to work again

Updated html snippet of youtube

---

events/Readme.rst
events/__init__.py
events/events.py
events/events_list.html

A plugin to generate an events list and a vCalendar file.

Event listing, alpha stage.

---

.gitmodules
Readme.rst

Hello,
I've created a plugin, called Panorama, to generate statistics from blog posts (number of posts per year, per categories and so on) and display them as beautiful charts.
- Statistics are made with the [Pandas Data Analysis Library](http://pandas.pydata.org)
- Charts are built with the [Python Wrapper for NVD3](https://github.com/areski/python-nvd3)
- A live example can be seen [here](http://aubonroman.com/stats.html).
I've built this plugin for my needs -- and for fun. It is not perfect but it may be useful to someone else -- or someone can contribute to improve it. Let me know.
Thanks,
Romain

Panorama v0.1

---

thumbnailer/Readme.md
thumbnailer/thumbnailer.py

May be not final version, but works for me and rather usefull.

Added option to save the file tree in the generation of thumbnailes.

---

render_math/Readme.md
render_math/math.py
render_math/mathjax_script_template

This solves #401 
Also made some slight changes to the documentation to make it easier to understand

Latex extensions for MathJax

---

pelican_comment_system/comment.py
pelican_comment_system/doc/feed.md
pelican_comment_system/doc/installation.md
pelican_comment_system/pelican_comment_system.py

Changes:
* preventing defining the defaults twice
* Adds a new feed
* Doc update

 [pelican_comment_system] Adds an feed which contains all comments of all articles

---

liquid_tags/Readme.md

Adds mention of SUMMARY_MAX_LENGTH as possible solution for issue with code generation

liquid_tags vimeo and youtube troubleshooting information

---

category_meta/category_meta.py

getpelican/pelican#1547 has been fixed, so don't monkey-patch the Content classes if it isn't necessary.
The workaround can be removed entirely once everyone who cares about this plugin is on a released version with the bugfix.
I was going to write a test suite along with this change but I failed to make unittests and Pelican play nice together, and I wasn't able to find a working plugin testsuite to crib from!  Anyhow, I've manually verified that this still works on the website that I use it for, with a version of Pelican that does *not* have the bug fixed.

Only apply workaround for issue 1547 if core exhibits the bug.

---

.gitmodules
Readme.rst

This plugin replace a text of a generated HTML.

Add plugin: replacer

---

asciidoc_reader/asciidoc_reader.py

Fix issue only #338 in the commit.

Fix unicode error for asciidoc #338

---

md_inline_extension/Readme.md
md_inline_extension/inline.py
md_inline_extension/pelican_inline_markdown_extension.py

Updated the documentation and fixed a subtle bug. It is now much easier to use and clearer to the user how to use.

md_inline_extension: update documentation and fix a bug

---

.gitmodules
Readme.rst
tag_cloud/README.rst
tag_cloud/__init__.py
tag_cloud/tag_cloud.py
tag_cloud/test_data/article_1.md
tag_cloud/test_data/article_2.md
tag_cloud/test_tag_cloud.py

* remove sort_tags plugin
* add tag_cloud plugin with added sorting functions

break out tag_cloud from core into plugin

---

render_math/math.py

Fixes an error with the beautiful soup code. With this fix, summaries will be correctly generated.

Process summaries working correctly with render_math

---

render_math/math.py

It was pointed out to me that I listening to the incorrect signals. This PR corrects this.

render_math: listen to correct signals

---

Readme.rst
authorpages/LICENSE
authorpages/README.md
authorpages/__init__.py
authorpages/authorpages.py

Requesting feedback on the approach. This basically works right now, but I'm not familiar enough with Pelican to know if I've implemented everything properly, or if I've missed something. All feedback appreciated.

New Plugin: Authorpages

---

interlinks/interlinks.py

Such that ppl can do:
```
```
It could be a temp workaround for https://github.com/getpelican/pelican/issues/812

[interlinks] support img src attr too

---

Readme.rst

Thanks for merging my pull request #490.  In this pull request you will find the appropriate for the Plugin Description table in the top-level Readme.rst file.

Add entry for the libravatar plugin in the Plugin Description table

---

sitemap/sitemap.py

Adds the ability to exclude a URL for being added to a sitemap (very common need).

Sitemap: ability to exclude URLs from a sitemap

---

sitemap/Readme.rst

Updating readme to explain how to exclude files from sitemap.

Update ReadMe to explain how to exclude files from sitemap

---

rmd_reader/Readme.md
rmd_reader/rmd_reader.py

rmd_reader updated to use MarkdownReader's default settings

---

render_math/math.py

Cleaner patch to resolve #514 .

address #514 by article postprocessing after internal links are resolved

---

video_privacy_enhancer/Readme.md
video_privacy_enhancer/video_privacy_enhancer.py
video_privacy_enhancer/video_service_thumbnail_url_generating_functions.py

Sorry -- after the [pull request](https://github.com/getpelican/pelican-plugins/pull/528) earlier today, I realized that I missed a few minor documentation updates.

Update documentation for Video Privacy Enhancer Plugin

---

org_reader/org_reader.el
org_reader/org_reader.py

Read author's name from org-mode file metadata

Read author from org file metadata

---

render_math/math.py

Sorry Justin, there was an indentation error in my last PR. This one will fix it. Really sorry.

render_math: fix indentation error

---

better_figures_and_images/better_figures_and_images.py

As per https://github.com/getpelican/pelican-plugins/pull/539#discussion_r37205169

Add exception for inline encoded images.

---

extract_toc/extract_toc.py

Previous commit broke Pandoc reader support, because multiple content readers are capable of handling **same** file extensions. It depends on which ones are enables and on the order which one processes the file.
This fixes the problem and improves detection of which content reader is used. An ideal solution would check exactly which reader class is used, but it seems this information is not available.

Fix and improve extract_toc support for Pandoc reader.

---

liquid_tags/notebook.py

I messed up in PR #543 and forgot to remove these two lines of debug code.

Liquid Tags plugin: remove debug code from #543

---

.gitmodules
Readme.rst

Adding my new [figure-ref](https://github.com/cmacmackin/figure-ref), [pdf-img](https://github.com/cmacmackin/pdf-img) and [pelican-cite](https://github.com/cmacmackin/pelican-cite) plugins.

Add figure-ref, pdf-imv, and cite as submodules

---

thumbnailer/thumbnailer.py

This fixes #489 (for me, at least).

thumbnailer: pass correct arguments to _resizer

---

headerid/README.rst
headerid/headerid.py

This adds support for configuring which char to use for headers anchor targets.

headerid: Make anchor target a configurable option

---

Readme.rst
sub_parts/README.md

Add Sub_parts to plugin list. Fix Markdown.

---

tag_cloud/README.rst

I struggled a little to put the tag cloud plugin to work, so I thought it would be nice to give more detailed instructions for those trying for the first time.

More info on how to install tag-cloud plugin

---

share_post/share_post.py

Long overdue. Fixes #577. Closes #598.
Ref:
* https://github.com/getpelican/pelican-plugins/issues/577
* https://github.com/getpelican/pelican-plugins/pull/556#issuecomment-140250725

share_post: fire on all_generators_finalized so that links resolve

---

gallery/README.md

Remove broken links. Fixes #521.

---

rmd_reader/rmd_reader.py

Instead of passing code to R some rpy2 functions have been used to keep the
code clear.
Rpy2 warnings have been suppressed.

rmd_reader: import knitr library via rpy2.importr

---

photos/photos.py
photos/test_photos.py

Fixes #607. Articles with embedded images now work when SITEURL has a path.

Photos: Handle SITEURL

---

photos/photos.py

… even though the tests passed!

Fix Photos bug with galleries and {filename}

---

render_math/math.py

render_math: Fix DOCUTILS_SETTINGS support 

---

Readme.rst

3 bugs resolved, comments added (pep8 passing on docstring conventions) and quick description on pelican-plugins README.

Ace editor plugin improvements

---

.gitmodules

A simple version generator which generates an incremented version file.
```
PLUGINS = [
'pelican_version'
]
VERSION_PATH = PATH + '/version'
OUTPUT_VERSION_PATH = 'output'
```

Add pelican-version plugin as submodule

---

sitemap/sitemap.py

Fix for issue #698.
Sorry that I've missed this one, but I tested with Python 2.7.
I am not able to test it right now. I added this PR if someone else need it asap and I will try to test it in the next 2 days.
Thanks @fxer for finding it and sorry for the headache :)

Fix sitemap plugin #698 for python3

---

events/events.py

Previously the events plugin and i18n_subsites could not be used together. Two issues had to be fixed:
1. Due to rewriting the output-path to a not already existing folder of i18n_subsites the events plugin failed with an IOError during writing the .ics file. Now we check the existance of the path before writing.
2. For a multi-language site we do also want to have multi-language calendars and not one calendar with every language in it (and thus, multiple events at the same time with differently named events although they are the same). To fix this I added some checks and when i18n_subsite plugin usage is detected we filter out duplicates of the events and create the calendar file on a per language base and not for the overall folder.

Make events plugin work with i18n_subsites

---

related_posts/related_posts.py

related_posts: Also fill article list for draft articles

---

extract_toc/extract_toc.py

Fixes #582
toc_extract assumes that if it can import pandoc_reader that
pandoc_reader is configured. This is not always the case and can cause
an error as pandoc_reader requires pelicanonf parameter.
This fix adds a plugin check to make sure that pandoc_reader was meant
to be called by having it as a configured setting.

extract_toc: Fix pandoc_reader issue

---

photos/photos.py

Per comment to PR #749 by @fufler. Here is the patch to fix python 3 compatibility.
@justinmayer I have not tested it as I do not have a python 3 environment. I can try to set one up and give it a go later this evening.

Photos: Fix Python 3 incompatibility

---

photos/README.md

This commit adds a bit more detailed example of blacklist.txt file.

[Photos] Updated documentation for blacklist.txt

---

photos/README.md
photos/photos.py

This commit adds support for parallel resize jobs. On multi-core processors usage of such facility significantly reduces resize time.

[Photos] Support for parallel photo resizing

---

jinja2content/README.md
jinja2content/jinja2content.py

...instead of looking for all templates in the theme's template folder.

jinja2content now accepts a configurable folder of local templates

---

.gitignore
plantuml/Readme.rst
plantuml/__init__.py
plantuml/generateUmlDiagram.py
plantuml/pandoc-plantuml
plantuml/plantuml_md.py
plantuml/plantuml_rst.py

* added support for Markdown syntax
* fixed some incompatibility with python 3.4
* added a filter to use plantuml with pandoc up to 1.16.0 excluded.

PlantUML: add support for Markdown syntax

---

rmd_reader/rmd_reader.py

Rename knitr object to KNITR for consistency

---

better_figures_and_images/better_figures_and_images.py

Add SVG support to better_figures_and_images using pySVG.

better_figures_and_images: Add SVG support

---

simple_footnotes/simple_footnotes.py

simple_footnotes: work with pages AND articles, remove dead code

---

pelican_comment_system/CHANGELOG.md
pelican_comment_system/Readme.md
pelican_comment_system/avatars.py
pelican_comment_system/pelican_comment_system.py

* Fixes <https://github.com/getpelican/pelican/issues/1949>
* Added a Changelog

[pelican_comment_system] Add support for the autoreload mode of pelican

---

liquid_tags/video.py

liquid_tag/video: add ability to specify width and height in percentages

---

events/events.py

In pull request #704 I already fixed some parts of the events plugin which did not work in combination with i18n_subsites. It turned out that there were even more issues and my commits did also not work with Python 3. This pull-request should fix this. In detail:
- Events were shown multiple times on the homepage (generated ical was correct, that was the first PR)
- Python 3 compatibility restored

Fixes for Events plugin

---

liquid_tags/Readme.md
liquid_tags/speakerdeck.py

Added a speakerdeck tag, as seen here:
https://github.com/TheNeuralBit/theneuralbit/blob/master/content/2014-07-19-viterbi-analysis.md
http://theneuralbit.com/viterbi-analysis.html

liquid_tags: added speakerdeck tag

---

Readme.rst
show_source/ReadMe.rst
show_source/__init__.py
show_source/show_source.py

Initial PR for the show_source plugin.

Add Show Source plugin

---

liquid_tags/liquid_tags.py
liquid_tags/notebook.py

because of the markdown changings.

liquid_tags: pelican 3.7 compatible

---

jinja2content/jinja2content.py

Fix also pelican-bootstrap3 in https://github.com/getpelican/pelican-themes/issues/460

jinja2content: Fix settings and extensions parsing proposed in #818

---

subcategory/README.md
subcategory/subcategory.py

As per my comment on #280 this should be the same implementation without the duplicate code. 
@vpiotr would you mind testing this to make sure it works as expected?
Is this the proper way to do this? I mean with the pull requests. I don't want to stomp on vpiotr's contribution.

subcategory plugin update, sub_path and sub_url

---

interlinks/interlinks.py

Fixes bad parsing of tags when trying to convert a/img tags.

Interlinks: Improve HTML tag handling. Fixes #885

---

Readme.rst
pelican_unity_webgl/LICENSE.txt
pelican_unity_webgl/README.rst
pelican_unity_webgl/UnityGameDirective.py
pelican_unity_webgl/__init__.py
pelican_unity_webgl/config.py
pelican_unity_webgl/template.txt
pelican_unity_webgl/test_unitywebgl.py

Easily embed Unity3d webgl games into posts and pages

Add Unity WebGL plugin

---

.gitmodules
Readme.rst

A plugin for estimating time that could be spent for an article reading.

Add ERT (estimated reading time) plugin

---

interlinks/interlinks.py

Sorry for the very looong wait to fix this silly bug.

Interlinks: patch to fix #920

---

Readme.rst
github-wiki/ReadMe.md
github-wiki/__init__.py
github-wiki/wiki.js
github-wiki/wiki.py
github-wiki/wikiarticle.html

A plugin that converts a flat GitHub wiki into a structured read only wiki on your site.

Add github wiki plugin and update readme

---

Readme.rst

Use latest version of just table plugin and update the plugin description

Just Table plugin: Update submodule

---

md_inline_extension/inline.py

Update plugin md_inline_extension to Pelican 3.7

---

simple_footnotes/simple_footnotes.py

@stuartlangridge I don't know if you have permissions to approve this pull request, but if yes please do it. It will be much faster than waiting for the feedback from other contributors for months.
Thanks!

[Simple Footnotes] Fix for error: "NameError: name 'unicode' is not defined" (Python3)

---

render_math/Readme.md

Correct minor typo in display math command syntax

Render Math: ReadMe fix

---

autopages/autopages.py

Linked to issue #951 the context seems to be missing ?

Autopages: Add context. Fixes #951

---

better_figures_and_images/better_figures_and_images.py

(Earlier request was against an older fork)
Current implementation did not work with {attach} ( or even images without an absolute path), because:
Assumed the item existed at output already
Could not deal with {attach} in name, did not remove and threw warning
The solution:
Does not assume file path is absolute, and does not require image to be copied yet.
If detects {attach} in filename-only then it will look relative to the current data file (.md for example) for reading properties.
Otherwise maintains the way it works now, have tested with data for example and the conditional only triggers when {attach} is seen, all else is as per existing.
@justinmayer please let me know your thoughts.

better_figures_and_images: Add support for {attach} images

---

assets/Readme.rst

Tuple causes error when used, must be list.

assets: ASSET_SOURCE_PATHS should be list instead of tuple

---

render_math/math.py

fix https://github.com/getpelican/pelican-plugins/issues/928
Fix is provided by jcbagneris.

render_math/math.py: fix build for pelican

---

optimize_images/Readme.md
optimize_images/optimize_images.py

Can drastically reduce the size of any svg image on your website by striping out editor tags for example and by minimizing the xml.

Svgo support for svg compression

---

share_post/README.md
share_post/share_post.py

New Features:
* Share on Hacker News added
Fixes:
* Documentation Fixed and Updated
* Code Refactored

Add HackerNews link to Share Post plugin

---

photos/photos.py

Downgrade logging to info when no optional info about images is found

---

gallery/README.md

[gallery] Update README.md

---

filetime_from_git/git_wrapper.py

filetime_from_git: Fix arguments encoding

---

plantuml/Readme.rst

Fix typo in PlantUML ReadMe

---

reddit_poster/__init__.py

Sometimes links were posted with random html in the title.
We make the code more robust by just always filtering out html

Use lxml to filter out html out of the title in the reddit post

---

pelican_comment_system/theme/templates/pcs/comments.html

Avoiding error of mixed active content.

pelican_comment_system: Link to jquery via HTTPS

---

Readme.rst

Also update the submodule to latest version.

Add missing description for Multi Neighbors plugin

---

tipue_search/README.md
tipue_search/tipue_search.py

Switch tipuesearch_content output from JSON to JS var

---

representative_image/Readme.md
representative_image/__init__.py
representative_image/representative_image.py
representative_image/test_representative_image.py

- Fix format issues in python and markdown files
- Fix #1124 Add options to representative image

representative_image: Add options and enhancements

---

author_images/README.md
author_images/author_images.py
author_images/generate_hashsum.py

Fixes python3 compatibility of the author_images plugin

author_images: Add Python 3 compatibility

---

org_reader/README.md
org_reader/org_reader.el
org_reader/org_reader.py

[org_reader] Support pelican status property

---

Readme.rst
shaarli_poster/README.md
shaarli_poster/__init__.py
shaarli_poster/requirements.txt
shaarli_poster/shaarli_poster.py
shaarli_poster/test_content/dummy_article.md
shaarli_poster/test_content/other_dummy_article.md
shaarli_poster/test_shaarli_poster.py

Could you get a look at this new plugin @justinmayer ? :)

Add plugin shaarli_poster

---

gzip_cache/test_gzip_cache.py

Tested with:
nosetests gzip_cache

Fix gzip_cache unit tests

---

simple_footnotes/test_simple_footnotes.py

Tested with:
nosetests simple_footnotes

Fix: test_simple_footnotes.py

---

jpeg_reader/test_exiv2_parser.py

Tested with:
nosetests jpeg_reader

Fix JPEG reader tests

---

pdf/pdf.py
pdf/test_pdf.py

Fix PDF plugin tests

---

libravatar/test_libravatar.py

Tested with:
nosetests libravatar

Fixing libravatar plugin tests

---

sub_parts/test_sub_parts.py

Tested with:
nosetests sub_parts

Fix sub_parts plugin tests

---

tag_cloud/test_tag_cloud.py

Tested with:
nosetests tag_cloud

Fix tag_cloud plugin tests

---

thumbnailer/test_thumbnails.py
thumbnailer/thumbnailer.py

Tested with:
nosetests thumbnailer

Fix thumbnailer plugin tests

---

photos/photos.py
photos/test_photos.py

Fix photos plugin tests

---

liquid_tags/soundcloud.py
liquid_tags/test_soundcloud.py

the soundcloud api doesnt listen on http anymore.

liquid_tags: Switch SoundCloud API links from http to https

---

.travis.yml

_cf._ https://github.com/getpelican/pelican-plugins/issues/1170

Remove a kludge in .travis.yml

---

sitemap/sitemap.py

Related to issue https://github.com/getpelican/pelican-plugins/issues/116.

Sitemap: Add support for custom URLs on standard pages

---

multi_part/multi_part.py
random_article/random_article.py
series/series.py
sitemap/sitemap.py
thumbnailer/thumbnailer.py
webring/webring.py

See: https://github.com/getpelican/pelican/pull/2763

Plugins shouldn't use root logger

---

more_categories/more_categories.py

This gets rid of some noise for anybody using the _more_categories_ plugin.

more_categories: silence printing the category slug

---

linker/Readme.md
linker/linker.py

Add `static` to list of builtin commands and add some explanation to readme file.

[linker] Remove warning for static links

---

Readme.rst

Add note about plugin migration to new organization

---

neighbors/Readme.rst

Add deprecation warning in the same spirit as: https://github.com/getpelican/pelican-plugins/commit/f8394e39df71f697c6879ef88e16f4d6d4bce614
Relates to:
* https://github.com/getpelican/pelican-plugins/issues/1287
* https://github.com/pelican-plugins/neighbors/pull/2

Add neighbors plugin migration disclaimer.

---

Readme.rst
assets/Readme.rst

Depends on: https://github.com/pelican-plugins/webassets/issues/2

[Migration] Flag webassets as migrated

---

Readme.rst
show_source/ReadMe.rst

Depends on https://github.com/pelican-plugins/show-source/issues/1

[Migration] Flag Show Source plugin as migrated

---

Readme.rst
read_more_link/Readme.md

Mark Read More plugin as migrated

---

asciidoc_reader/asciidoc_reader.py

Add DEBUG log output to make debugging asciidoc issues easier.

AsciiDocReader: Add DEBUG logging

---

asciidoc_reader/asciidoc_reader.py

[asciidoc_reader]: Rehandle file names with spaces

---

org_reader/README.md
org_reader/org_reader.el
org_reader/org_reader.py

@see https://docs.getpelican.com/en/latest/faq.html#how-do-i-assign-custom-templates-on-a-per-page-basis

org_reader: Add support for custom templates
