gzip_cache/gzip_cache.py
* Don't compress WOFF files.  This font format has internal compression;
gzip can often shave a few more bytes off but it's not worth the overhead.
* For any type of file, only save the compressed version if compression
actually made it smaller.
=> Adjust rules for what gets compressed by `gzip_cache`.

category_meta/README.md, category_meta/__init__.py, category_meta/category_meta.py
Resubmission of the `category_meta` plugin, which allows definition of arbitrary metadata for each category -- see the README for details.  Now with no extraneous commits!
=> New category_meta plugin (take two)

w3c_validate/README.md
adds a simple instruction message. useful for neophytes who might confuse w3c_validate vs wc3_validate from the `wc3_validate.py` file vs the plugin name.
re-do of pull request https://github.com/getpelican/pelican-plugins/pull/397 for neatness.
=> adds instruction to w3c_validate

assets/assets.py
Allow to explicitly set debug mode instead of relying on the logger. Running `--debug` in pelican only changes the logging so it can be used in production however with this using the logger to change how assets work I can no longer use it in production (which is needed for other reasons). So this change is to allow more control.
I haven't tested or anything, about to make the change myself and use it. However adding code here should easily show you what  I mean if you want to implement it a different way.
=> Assets: Allow to explicitly set debug mode

render_math/Readme.md, render_math/math.py, render_math/mathjax_script_template
Ability for automatic line breaks to be controlled in the plugin configuration
=> Mathjax configuration option: Allow automatic line breaks

org_reader/LICENSE, org_reader/README.md, org_reader/__init__.py, org_reader/org_reader.el, org_reader/org_reader.py
org_reader plugin, for reading Emacs Org-mode files for publishing as articles in Pelican.
=> org_reader plugin. Publishes Emacs Org-mode files.

render_math/Readme.md, render_math/math.py, render_math/mathjax_script_template
The mathjax plugin does not behave well for responsive sites. This is a difficult problem to solve fully, but it can be alleviated by setting automatically setting line-breaks, aligning displayed math to the left and ensuring no indent.
This change allows a user to specify if repsonsive should be attempted (defaults to false for backwards compat) . It also allows the user to set the responsive breakpoint
=> render_math responsive mode

Readme.rst
Replaces the pelican-md-metayaml plugin with an updated fork of it.
=> Replace pelican-md-metayaml with an updated version

render_math/math.py
When markdown is not installed on the system, the render-math plugin doesn't work because it tries to import markdown.
I added exception handling so that users who don't use markdown (yet) can still use this plugin.
PS: I hope it is ok to create the pull request here instead of @barrysteyn 's personal repository...
=> Allow render-math plugin to work for reST if Markdown is not installed

extract_toc/extract_toc.py
BeautifulSoup produces some `<html>` and `<body>` tags that need to be removed.
=> remove undesired <html> and <body> tags in extract_toc

thumbnailer/test_thumbnails.py, thumbnailer/thumbnailer.py
When ```pelican.settings.IMG_PATH``` has a trailing slash, Thumbnailer chops off the first letter of the thumbnail name. This PR contains a failing test demonstrating the issue:
```
AssertionError: 'sample_image_square.jpg' != 'ample_image_square.jpg' 
```
This PR then fixes the bug.
=> Fix bug in Thumbnailer When IMG_PATH has trailing slash

org_reader/org_reader.el
json is needed for org_reader to work. This seems the natural place to ensure this dependency is fullfilled.
Solves the issue discussed in issue #1668.
=> Add (require 'json) to org_reader.el

summary/Readme.rst, summary/summary.py
I implemented all these changes while debugging a problem with my blog ... which turned out to be `read_more_link`'s fault, but it wound up being easier to add a feature to `summary` enabling me not to *need* `read_more_link`, than to fix `read_more_link`.  And I think these changes are worthwhile in their own right.
* New feature: `instance.has_summary` set to True if an explicitly-defined
summary exists, False otherwise.  Templates can use this to inject a
"read more" link for instance (the `read_more_link` plugin seems to be
broken under Py3k).
* Tested under Python 3.4; import unicode_literals for consistent behavior
on both Py2 and Py3.
* `instance._content` is modified directly instead of using the undocumented
`instance._get_content` hook.
* Control flow within …
=> Overhaul Summary plugin for efficiency, Py3k compatibility, less convoluted control flow

Readme.rst, md_inline_extension/Readme.md, md_inline_extension/__init__.py, md_inline_extension/inline.py, md_inline_extension/pelican_inline_markdown_extension.py
This plugin allows a user to easily create a customized inline html expression for markdown. Markdown has things like `*` as inline expression, this plugin will allow a user to create whatever new inline expression they want.
I have been using this plugin privately for myself for quite a while, and I realized how useful I find it. So I decided to give it to everyone else. For example, I use it to highlight text in markdown
=> Add plugin for customized inline HTML for Markdown

better_figures_and_images/better_figures_and_images.py
This fixes the case where RESPONSIVE_IMAGES is not set and you get
errors like this:
ERROR: Could not process ./my-blog-post.md
| u'RESPONSIVE_IMAGES'
=> Better Images: Prevent errors when RESPONIVE_IMAGES is not set.

.gitmodules, Readme.rst
Differences between pelican-toc and pelican-extract-toc
`extract-toc` uses a markdown extension to generate a toc and then extract it via beautifulsoup. This extension generates the toc itself, removing the need to write `[ToC]` in your articles.
=> add toc plugin

render_math/Readme.md, render_math/math.py, render_math/mathjax_script_template, render_math/pelican_mathjax_markdown_extension.py
This plugin is not compatible with Python 3. This PR will fix this problem. It also adds two new features
1. mathjax_fonts - allows the forcing of fonts on the math
2. auto_insert - allows template designers control over whether the mathjax script is automatically inserted
=> render_math: Python 3, auto insert, and mathjax fonts

textbundle/Readme.md, textbundle/textbundle.py
I added some more documentation to the textbundle plugin's README and provide a shell function to create new articles in textbundle format.
=> Extend textbundle plugin documentation

render_math/Readme.md, render_math/math.py
This PR does two things:
1. Inserts the mathjax script so that math in the summaries will be rendered
2. Restores math that are cut off in the summaries: Pelican can cut math in half when creating its summary. This will result in math not rendering correctly. This PR will fix this state of affairs: If a summary contains math that is cut off, the math will be restored.
=> Render math now works properly with summaries

filetime_from_git/README.rst, filetime_from_git/filetime_from_git.py, filetime_from_git/git_wrapper.py
The filetime_from_git plugin relies on a now old version of gitpython.
However its not so easy as updating to the latest version as your
gitpython version must match your distros git binary for everything to
work.
This refactor restructures the plugin to provide some isolation from
this issue by wrapping the gitpython module in a simplified wrapper to
handle this difference.
I have also added the GIT_FILETIME_FOLLOW option which allows the
filetime module to follow files across renames.
As far as I can tell this can supersede pull request #378 and fix issue #384
=> Refactor filetime_from_git and add GIT_FILETIME_FOLLOW option

rmd_reader/rmd_reader.py
on windows machines, rmd filenames that include `c:\Users` will raise an error unless `\` are replaced with `\\`
=> rmd_reader: handle backslashes in filenames

liquid_tags/Readme.md, liquid_tags/gram.py
Instagram Image Tag
-------------------
By [Tom Spalding](https://github.com/digitalvapor)
You can see a working example at [antivapor.net/instagram-tag.html](http://antivapor.net/instagram-tag.html).
Based on [Liquid Image Tag](https://github.com/getpelican/pelican-plugins/blob/master/liquid_tags/img.py) by [Jake Vanderplas](https://github.com/jakevdp).
Optional Todo:
* Query JSON to automatically include descriptions.
http://api.instagram.com/oembed?url=http://instagr.am/p/olw8jXiz1_/
and option to add wrapping anchor link to original http://instagram.com/p/olw8jXiz1_
* Default to size m
http://instagr.am/p/olw8jXiz1_/media/?size=t
http://instagr.am/p/olw8jXiz1_/media
* Provide examples using with [Better Figures and Images](https://github.com/getpelican/pelican-plugins/tree/master/bette …
=> Add liquid tag for Instagram

libravatar/libravatar.py, libravatar/test_libravatar.py
This allows to honor the eventual "None" value of the LIBRAVATAR_SIZE
variable and transforming it into an string only after its value has
been asserted.
Also, add a unit test for exercising the LIBRAVATAR_SIZE variable.
=> Delay the string casting of the size parameter

libravatar/Readme.md
Please, merge this commit, which only changes the formatting of Markdown code blocks in the Readme.md file.  I was using the code block conventions of Pelican, which obviously does not work on Github.  I am using now fenced code blocks.
=> Libravatar: use fenced code blocks

tipue_search/README.md, tipue_search/tipue_search.py
As per [official documentation](http://www.tipue.com/search/docs/?d=20) `loc` field has been renamed to `url`.
=> Update for tipue search 5

libravatar/libravatar.py
With Python 3, the libravatar plugin yields the following error:
Unicode-objects must be encoded before hashing
This is caused by the fact that the email string obtained from the header of the content file is stored as a Unicode object in the metadata list in Python 3.  The string must then be encoded before being passed to the `hashlib.md5` function.  According to the current standard, only ASCII characters should appear in email addresses, so encoding `metadata['email']` into ASCII will make the plugin work with both Python 2 and Python 3.
=> libravatar: Encode email address before hashing

representative_image/representative_image.py
I might be wrong, but I don't see why only Articles could use featured images. So I expanded it to Articles, Pages and Drafts.
=> representative_image plugin. Let all kinds of pages use featured images.

txt2tags_reader/LICENSE, txt2tags_reader/README.md, txt2tags_reader/__init__.py, txt2tags_reader/txt2tags_reader.py
Would you mind if I add this txt2tags reader into the 'pelican-plugins' repository? I don't find any existing plugin for this. Please correct me if I am wrong.
=> Add txt2tags reader plugin

org_reader/README.md
It is necessary to use a date format org understands. Therefore the `<>` around the date. Otherwise it won't be recognized as org-property and the date will always be set to 11 January 2030.
=> org_reader: Correct date format info in README

share_post/share_post.py
added share to linkedin support, I'll add some new features like enable/disable links and order settings (all optional with default values) via pelicanconf.py
salu2.
=> share_post plugin: add share-to-linkedin support

Readme.rst, always_modified/README.md, always_modified/__init__.py, always_modified/always_modified.py
Say you want to sort by *modified* date/time in a theme template, but not all your articles have modified date/timestamps explicitly defined in article metadata. This plugin facilitates this sorting by assuming the modified date (if undefined) is equal to the created date. _[Description edited as noted below —J.]_
=> Add always_modified plugin

filetime_from_git/git_wrapper.py
GitPython renamed the method `commits` of object `Repo` to `iter_commits`. This
has been adressed in commit 47269dd35b9236de7fc84fa99fb9e41c8d975c05
But additionally the attribute `path` has been changed to `paths`. This has
been omitted in the previous commit and is fixed here.
See also [this comment by @a3nm][1].
[1]: https://github.com/getpelican/pelican-plugins/issues/384#issuecomment-68179848
=> Fixed usage of `iter_commits` in `git-wrapper.py`

render_math/Readme.md, render_math/math.py
Just updated the documentation and some code comments to reflect the new changes.
=> Update render_math documentation and comments

clean_summary/clean_summary.py, read_more_link/read_more_link.py, representative_image/representative_image.py, share_post/share_post.py, summary/summary.py
`clean_summary`, `read_more_link`, `representative_image`, `summary` plugins now use `all_generators_finalized` signal so as to avoid issue #314. They fallback to current behavior if said signal is not yet available.
See also: https://github.com/getpelican/pelican/pull/1616
=> Have relevant plugins use all_generators_finalized signal

summary/summary.py
The summary plugin crashed for me due to missing PagesGenerator import. importing it explicitly Resolves the issue
=> Add missing PagesGenerator import to Summary plugin

better_figures_and_images/better_figures_and_images.py, extract_toc/extract_toc.py, post_stats/post_stats.py, slim/slim.py, tipue_search/tipue_search.py
**This is untested (except for better_figures_and_images, which is how I encountered this bug).**
Beautiful Soup was (silently) using the lxml parser in the better_figures_and_images plugin, and that was resulting in extraneous wrapping with "\<html\>\<body\>" of page.content. According to [the BS docs](http://www.crummy.com/software/BeautifulSoup/bs4/doc/#differences-between-parsers), 'html.parser' is the (non-invasive) parser behavior we want.
Thanks to Avaris and winlu in #pelican for helping track down the root cause of this bug.
---Alex
=> Always specify parser for Beautiful Soup; fixes extraneous tags

video_privacy_enhancer/Readme.md, video_privacy_enhancer/video_privacy_enhancer.py, video_privacy_enhancer/video_privacy_enhancer_jquery.js, video_privacy_enhancer/video_service_thumbnail_url_generating_functions.py
Updated the Video Privacy Enhancer plugin, which downloads thumbnails of videos so that users don't get tracking cookies embedded on their systems until they explicitly "opt-in" to watching the video by clicking the thumbnail, at which point the image is changed into the actual iframe video embed. YouTube and Vimeo are now both supported (with the shortcodes `!youtube(video_id)` and `!vimeo(video_id)`, respectively), and the plugin and its documentation are now *much* easier to extend for other video services.
=> Update plugin to enhance privacy with video embeds

render_math/Readme.md, render_math/math.py, render_math/mathjax_script_template
Will not leave cdn protocol as a default value of the document's protocol. Now, user can force tls protocol and document protocol will be forceably pre-pended to CDN.
=> render_math plugin: force_tls option, prepend protocol to CDN

.gitmodules
Slight adaptation of [pandoc_reader](https://github.com/liob/pandoc_reader) for independent support of emacs org mode files.
=> Add org_pandoc_reader submodule

liquid_tags/diag.py, liquid_tags/graphviz.py, liquid_tags/mdx_liquid_tags.py
Hi, 
in order to add some **graphviz**/**blockdiag** liquid tag, I had to first add *multiline* regexp support to liquid tags. Now I'm able to add liquid tags which match more than one line. 
Some **graphviz** examples:
```
{% graphviz 
dot {
digraph graphname {
a -> b -> c;
b -> d;
}
}
%}
{% graphviz 
twopi {
<code goes here>
}
%}
```
Some **blockdiag** examples:
```
{% blockdiag {
blockdiag {
A -> B -> C;
B -> D;
}
}
%}
{% blockdiag {
packetdiag {
0-7: Source Port
8-15: Destination Port
16-31: Sequence Number
32-47: Acknowledgment Number
}
}
%}
```
Please let me know if you have futher questions. 
Cheers, Victor
=> Liquid Tags: Multiline regexp, graphviz & blockdiag support

better_tables/LICENSE, better_tables/README.md, better_tables/__init__.py, better_tables/better_tables.py
Simply, this plugin removes the extraneous elements and attributes that rst->html generates. Without this cruft, the tables pass HTML5 validation and make life /much/ easier when styling with CSS.
The real fix is to get rst2html5 merged, but sadly that is beyond both my skillset and time/effort availability.
---Alex
=> Add better-tables pelican plugin

better_figures_and_images/better_figures_and_images.py
Adds a simple exception for images which are encoded in-line (base64, etc). This allows Better Fig. to be used with the [Graphviz](http://blog.dornea.nu/2014/11/13/using-graphviz-with-pelican-and-liquid-tags/) plugin (which is exactly my use-case, heh).
=> Add exception for in-line encoded images

liquid_tags/notebook.py
This is an attempt to improve compatibility with v4.0 of the IPython / Jupyter packages.
* #536: this is due to dependancies I believe, see amended pip install instruction in the README.md
* #531: this is due to the split of IPython into python specific project (IPython) and notebook and associated utilities (Jupyter). See changes in notebook.py
* I did this by adding a layer of try:/import/except on top of the existing ones. It's brute force but it works though using the correct import after doing a version check might be preferable. Only one change was breaking the module as the nbformat module was called directly instead of being imported so there was no chance the shim provided by IPython 4.0 to ensure backward compatibility. The other changes fix the shim warnings.
* added another …
=> Improve ipython forward compatibility (v4.x), also ref #542, #536

render_math/Readme.md, render_math/math.py, render_math/mathjax_script_template
Two additions:
1. User can now control message_style attribute of mathjax
2. Translations are now also included for rendering math
=> Ability to hide mathjax message and render math in translations

share_post/share_post.py
Otherwise code would not compile (`summary` variable is still used)
Closes #549
=> share_post: Reverting removal of summary for the plugin to be usable

liquid_tags/Readme.md, liquid_tags/soundcloud.py, liquid_tags/test_soundcloud.py
The soundcloud plugin uses the official soundcloud API to get the widget
html tag. Also added tests.
=> liquid_tags: Add soundcloud plugin

asciidoc_reader/asciidoc_reader.py, asciidoc_reader/test_asciidoc_reader.py
Currently, the AsciiDoc plugin's handling of attributes does not work with list values, such as tags. For example, the unit test currently gives the following error:
```
$ python2 -m asciidoc_reader.test_asciidoc_reader
F.
======================================================================
FAIL: test_article_with_asc_extension (__main__.AsciiDocReaderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/media/D/Projects/Active/blog/pelican-plugins/asciidoc_reader/test_asciidoc_reader.py", line 47, in test_article_with_asc_extension
'Actual: %s') % (key, value, page.metadata[key]))
AssertionError: Metadata attribute 'tags' does not match expected value.
Expected: [u'Linux', u'Python', u'Pelican']
Actual: [<Tag 'L'>, <Tag …
```
=> Fix parsing of AsciiDoc attribute values by converting to unicode.

tipue_search/tipue_search.py
In korean windows environment, below error occur if use tipue_search.
```
CRITICAL: UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 3786: illegal multibyte sequence
Traceback (most recent call last):
File "c:\python34\Lib\runpy.py", line 170, in _run_module_as_main
"__main__", mod_spec)
File "c:\python34\Lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\devel\libsora.so\.venv\Scripts\pelican.exe\__main__.py", line 9, in <module>
File "c:\devel\libsora.so\.venv\lib\site-packages\pelican\__init__.py", line 456, in main
pelican.run()
File "c:\devel\libsora.so\.venv\lib\site-packages\pelican\__init__.py", line 183, in run
p.generate_output(writer)
File "C:\devel\libsora.so\ext\pelican-plugins\tipue_search\tipue_search.py", line 99, in generate_output …
```
=> Fix tipue_search crash due to encoding mismatch

code_include/__init__.py
This PR makes code_include plugin compatible with python3 import statement syntax.
=> Relative import for code_include

liquid_tags/graphviz.py
In liquid_tags plugin, the `graphviz` tags produces incorrect HTML that doesn't align the diagram as intended. This PR fixes it.
=> liquid_tags: Fix alignment in {% graphviz %} output

tipue_search/tipue_search.py
The last update only fixed the index for articles, while leaving pages in the old format.
=> tipue_search: fix also for template pages

liquid_tags/include_code.py
(*Edited, now with optional codec selection*)
This pull request solves the long-standing issue that `include_code` does not support files not being written in ASCII. Any UTF8 (or other non-ASCII) character will currently cause an exception and subsequently a pelican crash.
The solution works by defaulting to UTF8 but allowing a codec option in the `include_code` tag:
```
{% include_code NCP380.py lang:python codec:iso-8859-1 %}
```
Basically it is an extension of the solution I proposed in https://github.com/getpelican/pelican-plugins/pull/189. This solution had the problem that non-UTF8 files still could cause a crash.
As UTF8 is a superset of ASCII, this solution guarantees full backwards compability to the ASCII-only `include_code` tag.
=> Fix non-ASCII code with include_code causing errors

liquid_tags/gram.py
There were a few things to change. I changed the import to get it
working under python3 for urlopen and used items() instead of iteritems().
=> liquid_tags: gram plugin Python 3 compatibility

pelican_comment_system/doc/avatars.md
Added commas to indicate a tuple in the example. 
Without them, loading of known author avatar will fail (at least it did for me).
=> Add commas indicating tuple to example

.gitmodules, Readme.rst
Adding a simple plugin which links the translation page/article back to the translated page/article.
=> Add Backref Translate plugin

liquid_tags/notebook.py
This is mainly so people will stop asking me why the plugin doesn't work :smile:
=> MAINT: add warning for IPython versions greater than 1.x

liquid_tags/notebook.py
=> fix typo: IPython->IPYTHON

.gitmodules, Readme.rst
Sort categories (tags) by the number of articles in that category (tag).
See a live example here:
http://jhshi.me/blog/categories/index.html
=> Add category_order plugin

Readme.rst, photos/README.md, photos/photos.py
Following suggestions by Stéphane Goujet:
- PHOTO_LIBRARY accepts tilde syntax, such as ~/Pictures.
- Missing galleries report an error.
- Photos are always sorted galleries, instead of just on Mac OS X.
- Markdown deviant syntax was fixed.
=> Add Photos to the plugin list, plus minor improvements

better_figures_and_images/better_figures_and_images.py
plugin name : better figures and images
if I use external url for image, it occur crash. Because, url is not local path. I add error handling.
```
```
```
DEBUG: Better Fig. src: /home/sora/develop/libsora.so/contenthttps://raw.github.com/if1live/rpi-mpd-controller/master/documentation/image.jpg
ERROR: Better Fig. Error: image not found: /home/sora/develop/libsora.so/contenthttps://raw.github.com/if1live/rpi-mpd-controller/master/documentation/image.jpg
WARNING: Could not process development/rpi-mpd-controller.md
[Errno 2] No such file or directory: u'/home/sora/develop/libsora.so/contenthttps://raw.github.com/if1live/rpi-mpd-controller/master/documentation/image.jpg'
```
```
WARNING: Better Fig. Error: img_path should start with either {filename}, |filename| or /static
DEBUG: Better Fig. …
```
=> Better Figures and Images plugin: Fix crash on external image links

.gitmodules, Readme.rst
This plugin pulls the page view information from Google Analytics and add the page view count as a meta of article or page.
See a live example here:
http://jhshi.me/
Note that each post has its own page view count.
=> Add ga_page_view plugin

better_figures_and_images/better_figures_and_images.py
my static file syntax, 
`{filename}../static/sample/sidetail-sora.gif`
```
path = '/home/haruna/devel/libsora.so/content'
image_path = '../static/sample'
image_filename = 'sidetail-sora.gif'
os.path.join(path, image_path, image_filename)
```
Pelican original static file syntax,
`{filename}/static/sample/sidetail-sora.gif`
```
path = '/home/sora/devel/libsora.so/content'
image_path = '/static/sample'
image_filename = 'sidetail-sora.gif'
os.path.join(path, image_path, image_filename)
```
os.path.join ignore previous path if path element is absolute path.
so, if img_path start with '/', os.path.join is broken. so remove first '/'.
This bug is caused by me. 
I did't use standard static file syntax.
My previous pull request works on only my document.
Previous code is `src = …
=> better_figures_and_images: bug fix: broken path by os.path.join()

pdf/pdf.py
rst2pdf can work without the settings the plugin referenced.
=> Make pdf-related settings not required

pdf/Readme.rst
This builds on @dpetzel's work and just adds a link to rst2pdf documentation for styles. I've also tried to make it clear that defining style paths is optional.
=> Fix the pdf plugin's documentation

Readme.rst, pdf/Readme.rst, pdf/pdf.py, pdf/test_pdf.py
Third iteration of the feature that adds support for exporting Markdown articles and pages to PDF.
Changes:
- Now only two commits
- Only check whether an md source generates a PDF output if Markdown is enabled (in test code)
=> PDF plugin: Add support for exporting Markdown articles as PDF. Refs #573

Readme.rst, section_number/Readme.md, section_number/__init__.py, section_number/section_number.py
For some themes, the relationship between different sections can be vague. This plugin add section number to the section title. To make it looks like below:
=> New plugin: section numbering

.gitmodules
Changed panorama git submodule url from git to https. In an effort to be able to use pelican-plugins as a submodule. 
Before when attempting to setup a github pages blog I got the error,   
> The submodule registered for `./panorama` could not be cloned. Make sure it's using https:// and that it's a public repo. For more information, see https://help.github.com/articles/page-build-failed-invalid-submodule.
So I made the panorama submodule url public, tested it and it worked for me.
=> Change Panorama plugin submodule URL scheme from git to https

Readme.rst, org_reader/README.md, org_reader/org_reader.el, org_reader/org_reader.py
support reading most relevant metadata from org header properties.
any further properties we should include?
**CAUTION:** this is backwards-incompatible: previously, the `CATEGORY` property was translated into *tags*, while now `CATEGORY` is translated into category, and for tags there's `PROPERTY: tags`.
I don't really like the `#+PROPERTY: key value` syntax here; however my elisp is at a very early stage, and I couldn't find out how to extract `#+TAGS: `, `#+MODIFIED: ` and the like directly.
Any improvements to elisp style and such are more than welcome =)
@ardekantur @dsteuer @zakkak
=> Org reader metadata

.gitmodules
Hi,
I didn't find a quick and simple way to use ace editor (ace.c9.io) on Pelican.
suddenly, I created a plugin who works well on markdown and restructuredtext.
I add some features:
* url anchor (after some help : https://github.com/ajaxorg/ace/issues/2824)
* declaring *ace editor* settings on traditionnal *pelicanconf.py*
=> Add ace-editor plugin as submodule

summary/Readme.rst, summary/summary.py, summary/test_summary.py
Makes it possible to only use the first paragraph of a post as its summary if no marker is found.
=> Summary: add SUMMARY_USE_FIRST_PARAGRAPH

org_reader/org_reader.el
The error below occurs when I do "make publish".
```
Symbol's function definition is void: org-export-get-environment
ERROR: Could not process ./2016-01-aerosolve-demo-image-impressionism.org
| CalledProcessError: Command '[u'/usr/local/bin/emacs', '-Q', '--batch', '-l', '/home/zhang/blog/plugins/org_reader/org_reader.el', '--eval', '(org->pelican "/home/zhang/blog/src/content/2016-01-aerosolve-demo-image-impressionism.org" \'html)']' returned non-zero exit status 255
```
I found the solution in https://github.com/getpelican/pelican-plugins/issues/461, and it works.
My envirment:
GNU Emacs 24.5.1
pelican 3.6.3
=> Org_reader plugin: fix org-export-get-environment is void

org_reader/README.md, org_reader/org_reader.el, org_reader/org_reader.py
If `#+LANGUAGE` is not in the ORG file, the default value is not None nor Empty, it will be the language of OS. This will change the filename to `{slug}-{language}.html`, and the ARTICLE_SAVE_AS in `publishconf.py` will not be used.
=> org_reader: move language's setting form `#+LANGUAGE lang` to `#+PROPERTY: LANGUAGE lang`

.gitignore, rmd_reader/rmd_reader.py, rmd_reader/test_rmd_reader.py
I modified the knitr setup in the rmd_reader plugin so that I could pass options to knitr_opt_chunk via a pelicanconf option KNITR_OPTS_CHUNK, e.g.
KNITR_OPTS_CHUNK = {
'fig.path': 'images/', 
}
Mostly I wanted to set fig.path, but it should work for a number of the other options that would make sense.
=> Add support for Knitr configuration options

rmd_reader/Readme.md, rmd_reader/rmd_reader.py
Variables to interact with knitr:
RMD_READER_KNITR_QUIET (True): knitr's quiet argument
RMD_READER_KNITR_ENCODING (UTF-8): knitr's encoding argument
RMD_READER_KNITR_OPTS_CHUNK (None): knitr's opts_chunk settings
RMD_READER_CLEANUP (True): remove the markdown file generated by knitr
Included the property `RmdReader.enabled` to work with the global variable `rmd`.
=> Add new knitr settings for rmd_reader plugin

Readme.rst, linker/Readme.md, linker/__init__.py, linker/content_objects.py, linker/linker.py, linker/mailto.py
This plugin allows to define custom linker commands in analogy to the builtin `{filename}`, `{attach}`, `{category}`, `{tag}`, `{author}`, and `{index}` syntax.
By default, it supports one additional linker command: `{mailto}`.
=> Add Linker plugin

custom_article_urls/custom_article_urls.py
When an article's `status` metadata attribute is `draft`, don't render to the `custom_article_urls` location. Instead, treat the article like any other draft and render to whatever `DRAFT_SAVE_AS` specifies.
Fixes getpelican/pelican-plugins#660.
=> custom_article_urls: correctly handle draft status

filetime_from_git/filetime_from_git.py
A really simple patch: `datetime_from_timestamp()` is not a function provided by the Git wrapper,
it's a module-level function of the calling module.
=> filetime_from_git: Fix bad function call

pelican_comment_system/Readme.md, pelican_comment_system/pelican_comment_system.py
- readme: Updates urls
- The main logic starts now with the `article_generator_finalized` signal.
This allows other plugins to access the comment information of the articles.
- uses the active writer (maybe replaced by other plugins) to write feeds (Don't recreate the default one multiple times)
=> [pelican_comment_system] Increase interoperability with other plugins

org_reader/README.md
If you use the default path of emacs `/usr/bin/emacs` as `ORG_READER_EMACS_LOCATION`, org_reader will not find relative packages, because the packages of `Emacs for Mac OS X` are installed in the folder `/Applications/Emacs.app/Contents`.
=> Update org_reader's README.md

liquid_tags/notebook.py, liquid_tags/pelicanhtml_3.tpl
Syntax highlighting in collapsible notebook input cells was broken for IPython >=3 as it called highlight2html instead of highlight_code.
Document the language switch for notebooks.
=> Fix syntax highlighting collapsible code

filetime_from_git/filetime_from_git.py
The filetime_from_git plugin needs to use relative imports; otherwise, it doesn't seem to work using Python 3.
=> filetime_from_git: Use relative imports

.gitmodules, Readme.rst
Nicolas P. Rougier[1] has done some great work making Bootstrap's features available as rst directives. This is merely packaging his work into a Pelican plugin.
Overall, it is much more featureful than the 'twitter_bootstrap_rst_directives' plugin and makes using Bootstrap's rows and columns actually possible in the content without descending into `.. raw:: html` spaghetti hell.
A nice outline[2] shows which features are supported so far.
There are some superfluous files, but I've kept the changes minimal in order to simplify the merging of future upstream development.
---Alex
[1] https://github.com/rougier/bootstrap-rst
[2] https://rougier.github.io/bootstrap-rst/
=> Add bootstrap-rat plugin as submodule

filetime_from_hg/README.rst, filetime_from_hg/__init__.py, filetime_from_hg/filetime_from_hg.py
this is mostly an adapted copy of filetime_from_git to target mercurial
repositories.
=> Add filetime_from_hg plugin

render_math/math.py
Here in China our network condition is poor, sometimes connection to mathjax cdns may stuck and prevent the equations from loading.
Thus I enabled changing of `source` settings in `render_math` plugin, allowing user to change urls to their preferred CDNs or mirrors in case of bad network condition.
=> Allow user to change mathjax urls in render_math

rmd_reader/Readme.md, rmd_reader/rmd_reader.py, rmd_reader/test_rmd_reader.py
Many improvements:
- New feature *rename plots* with configuration variable `RMD_READER_RENAME_PLOT`. This helps renaming figures avoiding naming conflicts among post.
- Code clean up and removed unnecessary imports
- Implemented py3 compatibility
- New configuration variable `RMD_READER_KNITR_OPTS_KNIT` that sets options into `knitr$opts_knit`.
- README.md updated
=> rmd_reader: New features and py3 compatibility

render_math/Readme.md
I would like to introduce LaTeX macros support (e.g. for `\renewcommand` and the limited macro definitions that MathJaX allows)
However, I need to update the documentation first because otherwise when discussing math display environments it seems to imply that some kind of user macro support already exists.
This patch clarifies that we are discussing supporting display math environment macros in particular, rather than arbitrary macros (which in the broad sense are not in any case supported by all our rendering backends)
=> render_math: clarify scope of macro support

sitemap/sitemap.py
As a developer I would like my template pages to be written in sitemap.xml
NOTE: I initially thought that Pelican will parse template pages as contents.Page, but it seems that's not true.
Let me know if you prefer me to implement this in a different way.
=> Sitemap plugin: Parse template_pages and write them in sitemap

rmd_reader/Readme.md, rmd_reader/rmd_reader.py, rmd_reader/test_rmd_reader.py
This commit changes the behaviour of RMD_READER_RENAME_PLOT variable such that it can be set to chunklabel to enable the default unnamed chunk renaming, or to directory to rename figures according to the path of the markdown source. The latter is intended to be used in conjuction with setting fig.path in knitr options. Alternatively the variable can be set to anything else to disable automatic renaming, in which case the chunks in markdown files must have unique names.
=> rmd_reader: Use relpath sans ext of markdown source as prefix for figures to avoid overwriting figures with same chunk name

rmd_reader/rmd_reader.py
Python3 doesn't have has_key() for dict anymore, should use key in dict instead.
=> rmd_reader: Fix for python3

asciidoc_reader/asciidoc_reader.py
The asciidoc api will return unset document attributes as empty strings. When set as metadata this will cause errors. This workarounds by pruning empty values before setting them as metadata.
=> asciidoc_reader: Don't add empty metadata values

liquid_tags/youtube.py
The liquid_tags youtube module will support both absolute and percent size of video player.
Now it's only possible to do: {% youtube VIDEO_ID 640 390 %}
Will be possible to do so as well: {% youtube VIDEO_ID 640% 390% %}
=> liquid_tags.youtube: change regex to support width & height in percents

photos/photos.py
The photos plugin works nicely for monolingual homepages. Together with i18n_subsites the galleries are processed once for each language, and an additional time for the initial page generation. This is of course not what should happen. The pictures are the same for a certain gallery independant of the language of the post which uses the gallery.
With this pull request I add some memoization to the photos plugin such that the galleries are only processed once and not multiple times.
Additionally I added the possibility of specifying multiple galleries for one post. This is as easy as putting them in the same :gallery: tag e.g. ```:gallery: {photo}folder1 {photo}folder2```
Please note that this feature does only work with the ```{photo}``` syntax and not with ```{filename}```
=> Photos plugin enhancement

pelican_comment_system/pelican_comment_system.py
https://github.com/getpelican/pelican-plugins/issues/714#issuecomment-219302129 :
> I'll add a warning if we processes a comment with an invalid parent.
> So in the future such errors are easy to detect.
=> [pelican_comment_system] Logs a warning if the parent of a comment can not be found.

filetime_from_git/git_wrapper.py
Fix filetime_from_git not working in python3 when `GIT_FILETIME_FOLLOW = True`. This fix uses list comprehension instead of map which works in both python2 and python3.
=> Fix filetime_from_git not working in python3

pelican_comment_system/theme/static/js/comments.js
=> [pelican_comment_system] Fix mailto link: use '\r\n' instead of '\n'

pelican_comment_system/comment.py
The direct `date` attribute of a Content object has always a timezone. 
Fixes #721
=> [pelican_comment_system] Fix comparison of offset-naive and offset-aware datetimes

better_figures_and_images/better_figures_and_images.py
The better_figures_and_images plugin stops with an error if it fails to open any image to parse its width. For example, this would happen with RMarkdown articles with SVG plots. Instead, according to [this article](http://tympanus.net/codrops/2014/08/19/making-svgs-responsive-with-css/) we could just set the width to 100%.
=> [better_figures_and_images] Default to 100% width if opening image with PIL fails (e.g. for SVG images)

Readme.rst, glossary/__init__.py, glossary/glossary.py, glossary/readme.md
By creating the `definitions` variable, visible to all page templates, which contains all information from definition lists (<dl> tags) found in articles.
=> Add Glossary plugin for definition lists found in articles and pages

glossary/glossary.py, glossary/readme.md
Also updated readme accordingly.
=> Glossary plugin: accept GLOSSARY_EXCLUDE as a setting to skip over some predefined definition lists

Readme.rst, jinja2content/README.md, jinja2content/__init__.py, jinja2content/jinja2content.py
This plugin is intended to replace [pelican-jinja2content](https://github.com/joachimneu/pelican-jinja2content/tree/f73ef9b1ef1ee1f56c80757b4190b53f8cd607d1) which hasn't been developed in a while and generated empty `<p>` tags in final html output.
=> Add jinja2content plugin, allowing the use of Jinja2 directives inside articles

rmd_reader/rmd_reader.py
The initialization options: --no-save, --quiet and --vanilla, have been set to create an clean R environment ignoring specific user settings.
In the early created R environment the locale has been set to "C" to avoid i18n problems while parsing data.
=> rmd_reader: set initialization options for R environment

asciidoc_reader/README.rst
Following discussion for issue 488 of pelican-plugins (getpelican/pelican-plugins#488)
=> Add AsciiDoc metadata format example

filetime_from_git/git_wrapper.py
Python 3 doesn't have izip_longest introduced in commit f5d897632977abd0ef9ea591347331e60063ffac -- apparently it's called zip_longest. For compatilibity with py2 and py3 this commit just implements the cookbook idiom (alternative 1) from 
http://python-future.org/compatible_idioms.html#itertools-filterfalse-zip-longest
Downside is that this requires the future package to be installed i.e. `pip install future`.
=> filetime_from_git: better py2 and py3 compatibility

simple_footnotes/simple_footnotes.py
Looks like html5lib module has been updated, and the plugin is broken. Here
is the way to fix that.
`'Attribute error: html5lib.serializer' has no attribute 'htmlserializer'`
=> simple_footnotes: Fix html5lib module problem

.gitmodules, Readme.rst
This change adds a `deadlink` plugin to manage links to pages that are not available anymore. It allows to replace original link with a link to proper archive.org query. It also allows to modify anchor tags of dead links by adding custom classes or appending bootstrap labels to them.
I hope you find it useful.
=> Add `deadlinks` plugin as a submodule

photos/photos.py
Hi,
I noticed that the galleries weren't displayed on translated pages. I found that generator.translations has been omitted from `photos.py` > `detect_images_and_galleries()`. Here is a quick patch to serve translation needs on pelican.
By the way thank you so much for such a nice extension!
=> Photos: add translation support

liquid_tags/graphviz.py
Fix byte string in python 3
`base64.b64encode` will output byte string in Python 3, and it breaks inline base64 image in HTML.
`decode('utf-8')` will convert a byte string into a string and make  python 2 be happy, too.
```
>>> print(base64.b64encode(b'\01'))
b'AQ=='
>>> print(base64.b64encode(b'\01').decode('utf-8'))
AQ==
```
=> liquid_tags > graphviz: Decode base64 output string to UTF-8

liquid_tags/include_code.py
When using Python3 calling .decode(codec) on a str is impossible.
We need to check against python's interpreter version to check
if we can decode or not the str.
=> [liquid_tags] include_code tag Python3 compatibility. Fixes #602

photos/README.md, photos/licenses.json, photos/photos.py, photos/requirements.txt
Added exif copy. Refactored jpeg rotate. Both now rely on piexif.
Added tool to keep exif if the original input photo was a jpg.
Added tool to remove gps data from jpeg exif.
Added debug option to disable multiprocess
Added tool to add copyright and artist information to jpeg exif.
Added tool to set default color on alpha channel images when they are converted to jpg.
Cleaned up README.txt.
=> Photos: Add ability to keep EXIF data on resize

.gitmodules
I changed my user name from Alexqw to aqw, and thus the repo locations have changed. The old link will redirect (GitHub's good about that), but it's still best to update it.
---Alex
=> Update upstream URL for bootstrap-rst

liquid_tags/video.py
Liquid tags wrap content in a **<p>** tag.
Unfortunaly, the **<p>** element represents a paragraph. It cannot contain block-level elements like **<div>** (https://www.w3.org/TR/html401/struct/text.html#edef-P)
All the browser trying to interpret this so
``` html
<p></p>
<div>
... my content
</div>
<p></p>
```
I suggest to replace **<div>** by a **<span>** tag.
=> convert <div> to <span> on a liquid_tag_video

liquid_tags/pygalcharts.py
Generate SVG graphs using PyGal
This has been incorporated into the existing liquid tags.
Syntax is simple as follows (based on the PyGal example graphs).
A pie chart:
```
{%
pygal {
"type": "pie",
"title": "Browser usage in February 2012 (in %)",
"data" : [
{"title": "IE",
"values": 19.5},
{"title": "Firefox",
"values": 36.6},
{"title": "Chrome",
"values": 36.3},
{"title": "Safari",
"values": 4.5},
{"title": "Opera",
"values": 2.3}
]
}
%}
```
Which renders as follows:
`<div class="pygal" style="text-align: center;"><embed type="image/svg+xml" src="data:image/svg+xml;charset=utf-8;base64,<base64-data>" style="max-width:1000px"></div>
`
It works completely in-line without any external files or resources and is displayed crisply and smoothly.
Attached is a PDF file generated from a .md blog …
=> liquid_tags: Add PyGal generation tag

subcategory/README.md, subcategory/subcategory.py
This PR adds support for folder-based subcategories, to remove the requirement to edit article files to edit/reorganise categories.
It is implemented based on providing an `PATH_METADATA` parameter to extract `subcategory_path` variable. Setting/unsetting this is sufficient to activate/deactivate folder-based subcategories. Using the regex allows for customisation of folder-subcategory hierarchy — e.g. to exclude specific subfolders, or adjust the hierarchy depth.
I've updated the `README.md` with an example of usage.
=> Subcategory: Add support for folder-based subcategories.

simple_footnotes/simple_footnotes.py
With the current versionof html5lib, the simple_footnotes plugin breaks with
an assertion failure. The root causes is that some strings in simple_footnotes
are unicode and others are str type. For html5lib to be happy, everything has
to be unicode.
This patch fixes the html5lib issue, and introduces no other issues I was able
to find.
=> simple_footnotes: Fix unicode errors triggered by latest version of html5lib

pelican_comment_system/CHANGELOG.md, pelican_comment_system/theme/static/js/comments.js
Please review this pull request in which I fixed a bug where the element
ID used in the jQuery expression was wrong.
=> pelican_comment_system: Fix element ID in cancelReply()

photos/README.md, photos/photos.py
* Add `{lightbox}` option for inline images, to insert image compatible with [Lightbox](http://lokeshdhakar.com/projects/lightbox2/), e.g.
* For use with other implementations, the gallery and caption attribute names can be set with `PHOTO_LIGHTBOX_GALLERY_ATTR` and `PHOTO_LIGHTBOX_CAPTION_ATTR`.
=> Photos plugin: Add lightbox option to inline photo replacement

pelican_comment_system/CHANGELOG.md, pelican_comment_system/Readme.md, pelican_comment_system/doc/import.md, pelican_comment_system/import/blogger_comment_export.py, pelican_comment_system/pelican_comment_system.py
at the request of the plug-in authors (see [the comment](http://blog.minchin.ca/2016/12/blogger-comments-exported.html#comment-1md)).
=> Pelican Comment System: add Blogger comments export script

render_math/math.py
to fix the lack of math markup in drafts mentioned in #805. (CC @MarkCWirt)
=> render_math: Handle math markup in drafts

pelican_comment_system/Readme.md
=> pelican_comment_system: Fix link to import comments

render_math/math.py
This extensions does not work with the current git version of pelican. This fix hopefully addresses the issue (works for me).
=> render_math: Fix for new MARKDOWN dict in Pelican 3.7

gzip_cache/gzip_cache.py
As per [this gist](https://gist.github.com/sergejmueller/cf6b4f2133bcb3e2f64a#good-to-know), woff2 is compressed also, so it should be excluded from the gzip cache as well.
=> gzip_cache: Exclude internally-compressed woff2

sitemap/Readme.rst, sitemap/sitemap.py
The plugin currently supports using regexes to make a case private. This adds the ability for a page author to mark a page as private, without mucking around in the settings for the entire site.
=> sitemap: Add ability to mark individual pages as private

video_privacy_enhancer/video_privacy_enhancer.py, video_privacy_enhancer/video_service_thumbnail_url_generating_functions.py
I upgraded my Pelican virtualenv this weekend to Python 3 and Pelican 3.7.1, and realized that the Video Privacy Enhancer breaks with the upgrade. Thus, I added use of the `six` package to support both Python 2 and 3. I then tested re-generating my site with Python 2.7.12 (with Pelican 3.6.3) and Python 3.4.5 (with Pelican 3.7.1).
=> Video Privacy Enhancer: Add Python 3 support

tipue_search/tipue_search.py
Fixes issue #590.
Relative paths in URLs stored in JSON will allow local use and testing on staging environments (and the like) of Tipue Search results.
=> tipue_search: Don't use SITEURL in JSON for search results

render_math/Readme.md, render_math/math.py, render_math/mathjax_script_template
As MathJax is closing its CDN, users are advised to use local version or another CDN, with cdnjs being preferred at the moment. Update link in plugin configuration and really close #881
=> Update render_math plugin to use cdnjs

headerid/__init__.py
=> Allow headerid plugin to work with Python 3.5.3

photos/README.md
=> "photos" plugin: README typo fixed in 'How to use' section

photos/photos.py
If we try to use EXIF manipulation, and a picture as no EXIF data, thumbnails and resized pictures are not created.
With this little error handling, a debug info is showed and everything continue, creating resized and thumbnails pictures.
=> Photos: Handle photos without EXIF data more gracefully

thumbnailer/test_thumbnails.py
Under the original circumstance, test method `path` can be confused with `path` attribute of `os` module.
By altering import syntax this way, it is immediately obvious path attribute is from os.
=> Thumbnailer: Modify os module import syntax

Readme.rst, pelican-rdf/ReadMe.md, pelican-rdf/__init__.py, pelican-rdf/pelican_rdf.py, pelican-rdf/sparql-queries/classes.sparql, pelican-rdf/sparql-queries/lov_metadata.sparql
This plugin offers a flexible mechanism to write lightweight documentation about rdf vocabularies, based on sparql queries. The core idea is to allow the user to both access right away to essential informations about the vocabulary, but also to allow him to extract custom information about its vocabulary. The usage of this plugin is demonstrated for instance on the page https://irit_ut2j.frama.io/, which is still a work in progress but shows the integration of the plugin into a gitlabl pages process.
=> Add RDF plugin to parse vocabularies and process them as a new media type

render_math/math.py
This PR is to fix the `NameError` I get when using MathJax extensions. The error comes from the line
filter(lambda string: isinstance(string, basestring))
Because `filter()` is a generator in Python 3, the lambda function doesn't actually called at the point of the `filter()` statement, it gets called later, outside the enclosing `try` block. I've changed this to identify the relevant string type in advance, at module level, so the new call to `filter()` doesn't raise this error.
I haven't created an issue in advance because this seemed like a very straightforward and simple fix.
=> [render_math] Fix NameError in Python 3

thumbnailer/Readme.md, thumbnailer/thumbnailer.py
With the help of the THUMBNAIL_INCLUDE_REGEX setting it is now possible to restrict thumbnailing to a files matching this regular expression. The setting is expected to be a string. If available, a regular expression is created. The default behavior is still that all files not starting with a dot are respected.
For instance, this can be set to only match files ending in "jpg", "jpeg" or "png" one can use:
THUMBNAIL_INCLUDE_REGEX = r'(jp[e]g|png)$'
This is useful to exclude other files that sometimes go along with images, e.g. titles.
=> Thumbnailer: add optional input file name regex setting

author_images/README.md, author_images/__init__.py, author_images/author_images.py, author_images/generate_hashsum.py
This plugin adds support for author.image and author.avatar properties, based on files found with appropriate naming. It searches the AUTHOR_IMAGES (or _AVATARS) path for files named appropriately, and then adds the locations of these files (if found) to author.images (or author.avatars) for use when displaying articles.
I'm not convinced it's ready for merging, I have a few questions which I cannot answer myself.
I don't know if I'm calling my function with the right signal. I've dug through the Pelican code, and tested many options, and I just can't work out how it all glues together. Currently it uses article_generator_finalized, but this feels too late as I not only have to iterate over all authors in the generator, but also all authors in each article in the generator.
I'm also …
=> Add author_images plugin

section_number/section_number.py
I run any command for build site, for example, `pelican content`.
Example of HTML page display:
```markdown
1 Sasha first header
1.1 Sasha first subheader
2 Sasha second header
```
Dots after headers numbers:
```markdown
1. Sasha first header
1.1. Sasha first subheader
2. Sasha second header
```
I think, that in English typography is customary to put dots like [**ordered lists**](https://daringfireball.net/projects/markdown/syntax#list). [**Example**](http://foundation.zurb.com/sites/docs/typography-base.html#header).
Also, I remove unused module and variable.
Thanks.
=> Section Number: Dots after numbers in headers

plantuml/plantuml_md.py, plantuml/plantuml_rst.py
Fixed plugin plantuml for pelican 3.7 (tested with pelican 3.7.0); fixed #833.
Fixed class attribute if markdown syntax (fixes #838)
=> PlantUML: Update plugin for Pelican 3.7+

filetime_from_git/git_wrapper.py
Paths with non-ascii characters would give encoding errors.
Fixes #328
=> filetime_from_git: Handle non-ASCII paths

category_meta/category_meta.py
`category.slug` is not writeable since [648165b839fe9562822fa843cbdbfe224b12dfbd](https://github.com/getpelican/pelican/commit/648165b839fe9562822fa843cbdbfe224b12dfbd).
=> category_meta: Add support for Pelican >= 3.7.0

tag_cloud/tag_cloud.py
TAG_CLOUD_MAX_ITEMS allows to limit the cloud size to the most used tags.
The current calculation of the tags step does not take this feature into account, resulting in almost all represented tags to belong to a single, highest step.
Let's say I have 5 steps, nearly all tags will belong to the fifth step, a few to the fourth, steps below will not be represented at all. All tags in the cloud appearing with the same size, the result is ugly.
This patch actively checks the minimum count value to ensure that tags are more evenly spread among all available steps.
If I keep the 5 steps example above, now tags are evenly spread along the five steps, producing a better cloud effect.
=> [tag_cloud] Better tags repartition when TAG_CLOUD_MAX_ITEMS is used

photos/photos.py
otherwise the image was being cut. See http://pillow.readthedocs.io/en/3.1.x/reference/Image.html#PIL.Image.Image.rotate for expand setting - this resizes the image when rotating.
It may be applicable to other orientations in this section of code, but I have no photos to test with.
See also https://stackoverflow.com/questions/31303938/how-do-i-stop-pil-from-swapping-height-width-when-rotating-an-image-90
=> [photos] Expand photo size when rotated

txt2tags_reader/txt2tags_reader.py
Important improvement of the txt2tags html output (remove not needed header and footer).
=> txt2tags_reader: Add --no-headers option

asciidoc_reader/asciidoc_reader.py
Hopefully these changes will help with issue #995. I was able to test using both Python 2/3 and everything seemed okay. This change also fixes and issue seen with titles/metadata not being rendered correctly in Python 3.
=> Fix Unicode problems reported in issue #995

tag_cloud/README.rst
Typo in `<span>.badge` in CSS selector in the example css configuration.
=> Improve tag_cloud README

.gitmodules, Readme.rst
Add plugin that gets information about a Meetup.com group from the Meetup API and makes it available for use in pages/articles.
=> Add pelican_meetup_info as submodule

render_math/Readme.md
I just add a couple spaces to get the headings to render properly
=> [render_math] Fix Markdown headings in ReadMe 

jinja2content/README.md, jinja2content/jinja2content.py
This is a thorough refactor of the jinja2content plugin that also adds some additional functionality.
- restructure Jinja reader as a mixin
- remove re-implementation of MarkdownReader.read
- add support for RST and HTML input through JinjaRstReader and JinjaHTMLReader
- update README to clarify functionalities
The plugin now works as follows. The mixin reads Jinja-specific settings during initialization. Then, when the reader's `read` method is called, the mixin reads the source file and renders it using the configured Jinja environment. Then, it writes the results to a temporary file and passes it on to the base reader classes. This is nice because the plugin doesn't have to make any assumptions about what the base reader class is doing, as long as it can pass a file name to the …
=> Update jinja2content plugin

liquid_tags/notebook.py
See: https://github.com/getpelican/pelican-plugins/issues/933
and in particular https://github.com/getpelican/pelican-plugins/issues/933#issuecomment-327721786
for more details.
Use improved MathJax setting and maintaining the async loading. This closes #933
Fixed async loading of page breaking mathjax
See https://github.com/getpelican/pelican-plugins/issues/933
for more details.
=> Improved integration of MathJax

liquid_tags/Readme.md, liquid_tags/generic.py, liquid_tags/liquid_tags.py, liquid_tags/test_data/content/test-generic-config-tag.md, liquid_tags/test_data/pelicanconf.py, liquid_tags/test_generic.py, liquid_tags/test_notebook.py, liquid_tags/tox.ini
Starting in #321, liquid tag sub-plugins (e.g. a new tag) that needed a config entry had to modify two arrays in the liquid-tag/ directory. This is sort of a pain for a sub-plugin that's not in the tree.
Here's a quick fix that looks into a user's pelicanconf.py for a LIQUID_CONFIGS array and makes those config files entries available to the plugin as well, ala:
```python
LIQUID_CONFIGS = (('PATH', '.', "The default path"), ('SITENAME', 'Default Sitename', 'The name of the site'), ('FOO', 'Default for foo', 'A nonsense test'))
```
(it's parameter, a default value, and then help text)
At some point, perhaps the hard-coded settings in LT_CONFIG could be moved into a default config file setting, but this PR should happily coexist with the settings that are already in LT_CONFIG out of the …
=> [liquid-tags] specify in conf which params should be passed sub-plugins

i18n_subsites/README.rst
The plugin calls for the extension for the command “gettext” and
doesn’t write the text without it.
=> Update i18n_subsites readme

tipue_search/tipue_search.py
This solves an issue stemming from the changes in #591 where the generated URLs are always relative, even when using RELATIVE_URLS as False in publishing settings.  This caused URLs showing up in the Tipue Search JSON file (and thus a frontend UI) to appear like `blog/about.html` when it should be `https://example.com/blog/about.html`; in short, whilst it works, it looks strange as there is no context.
This fixes the issue by adhering to RELATIVE_URLS; if set as `True` (eg dev/testing), the existing behaviour is applied.  If set as `False` (eg for production use), then the full site URL is created using pre-#591 behaviour.
=> tipue_search: adhere to RELATIVE_URLS setting for URL generation

render_math/math.py
Since Pelican 3.7, render_math no longer is able to process summaries.
Simply fixing the deprecation warning (#850, #858) does not solve this issue, as the `get_summary` function is memoized using `pelican.util.memoize`.
As a workaround, the memoize instance is acquired by inspecting the result of `memoize.__call__` and  its cache subsequently is cleared.
The following assumptions are made, which might not hold for future versions of pelican:
- `article.get_summary` is an instance of `functools.partial`
- the function bound by this instance is a bound method of an `pelican.util.memoize` instance
- `pelican.util.memoize` has a member `cache` that stores the memoization
=> Render Math: Workaround for processing summaries

photos/README.md, photos/photos.py
Arranging thumbnails of pictures with different aspect ratios in page is always a problem. This merge request allows to use the solution picked by Instagram: cropping thumbnails as squares.
An example of this feature can be found on my [personal page](https://lemanchet.fr/photography.html).
=> Allow photos plugin thumbnails to be cropped as squares

liquid_tags/b64img.py
The following error occured when used with python3
ImportError: No module named 'urllib2'
=> Add support for python3 in liquid_tags/b64img.py

render_math/math.py
Update MathJax source to point to latest version (2.7.3 instead of 2.7.0).
=> render_math: Update MathJax to latest version 2.7.3

interlinks/interlinks.py
I'm using Python 3 now but doing test builds against  2.7 to check for compatibility issues for anyone who's still on 2.7. I noticed the following error from the interlinks plugin;
```
| UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 71: ordinal not in range(128)
|___
| Traceback (most recent call last):
|   File "/mnt/sdd_store/cscutcher/myrepos/website/cscutcher.gitlab.io/.tox/py27/lib/python2.7/site-packages/pelican/generators.py", line 523, in generate_context
|     context_sender=self)
|   File "/mnt/sdd_store/cscutcher/myrepos/website/cscutcher.gitlab.io/.tox/py27/lib/python2.7/site-packages/pelican/readers.py", line 572, in read_file
|     context=context)
|   File "/mnt/sdd_store/cscutcher/myrepos/website/cscutcher.gitlab.io/.tox/py27/lib/python2.7/site-packag …
```
=> interlinks: UnicodeDecodeError: 'ascii' codec can't decode byte... on python 2.7

filetime_from_git/actions.py, filetime_from_git/content_adapter.py, filetime_from_git/git_wrapper.py, permalinks/permalinks.py
The interface for hashlib.update changed to require input supporting [the buffer API](https://docs.python.org/3/c-api/buffer.html).    Also `.next` no longer exists in python 3.
Should fix issue #1011
=> permalinks and filetime_from_git: Py3 compatibility fixes. Fixes #1011

better_figures_and_images/better_figures_and_images.py
```
|   File "~/git/plugins/better_figures_and_images/better_figures_and_images.py", line 77, in content_object_init
|     if src is None:
| UnboundLocalError: local variable 'src' referenced before assignment
```
=> better_figures_and_images: Fix "local variable 'src' referenced before assignment"

sitemap/Readme.rst
Thanks for the plugin; ping it forward with a doc update..
The sample as-is, 'pelican.plugins.sitemap ' would not load. What I have provided works. I also added the path statement as an extra helper.
=> SiteMap: Updated sample

Readme.rst, ctags_generator/README.md, ctags_generator/__init__.py, ctags_generator/ctags_generator.py, ctags_generator/test_content/article_with_duplicate_tags_authors.md, ctags_generator/test_content/article_with_markdown_and_nonascii_summary.md, ctags_generator/test_content/article_with_md_extension.md, ctags_generator/test_ctags_generator.py
The goal is to provide tags autocompletion in all editors that support ctags (e.g. `vim` natively).
Here is an example of simple integration of such tags completion in Notepad++ using the "Python Script" plugin:
```
import os
ctags_filepath = os.path.join(os.path.dirname(notepad.getCurrentFilename()), 'tags')
if os.path.exists(ctags_filepath):
with open(ctags_filepath) as ctags_file:
ctags = set(line.split('\t')[0] for line in ctags_file.readlines() if not line.startswith('!'))
editor.autoCShow(0, ' '.join(sorted(ctags)))
```
When bound to a shortcut, this will provide autocompletion of existing articles tags.
=> Adding ctags_generator plugin

filetime_from_git/git_wrapper.py
Otherwise peoples `~/.gitconfig` could cause commands in the wrapper to
fail.
=> filetime_from_git: Sanitise git environment when using `git_wrapper`

.gitmodules, Readme.rst
The [Similar Posts](https://github.com/davidlesieur/similar_posts) plugin adds a list of similar articles to each article's context.
=> Add the Similar Posts plugin

ctags_generator/ctags_generator.py
A bug in `ctags_generator/ctags_generator.py` blocked the generation of `pages` whenever this plugin was used with `WRITE_SELECTED = []` in the settings
=> Fix bug in ctags_generator.py

Readme.rst, more_categories/README.md, more_categories/__init__.py, more_categories/more_categories.py, more_categories/test_data/article_with_multiple_categories.rst, more_categories/test_data/article_with_no_category.rst, more_categories/test_more_categories.py
Plugin that allows for multiple categories per article plus nested categories (`foo/bar`, `foo/baz`)
=> Add more_categories plugin

i18n_subsites/i18n_subsites.py
pelican 4 introduces `draft` as allowed status for articles and removes `Draft` from `pelican.contents`.
i18n_subsites does not work any more with version 4.x. This MR fixes this
=> i18n_subsites: Use new draft status for articles

i18n_subsites/i18n_subsites.py
Fixes https://github.com/getpelican/pelican-plugins/issues/1087 (hopefully)
The `i18n_subsites` tests are broken in multiple ways, so I've found it impossible to test whether this is backwards compatible, but it should be.
=> i18n_subsites: Accommodate filename renaming to static_content in generator context

org_reader/org_reader.el
This should fix the error indicated in Issue #1065. The `htmlize` package is needed for Emacs to process SRC blocks in org files, but it is not included in the default installation of Emacs.
It sets up the `htmlize` package for Emacs to use. I also tested this code after deleting the package -- if `htmlize` is not installed, the same error occurs as described in #1065.
I also cleaned up some of the lisp formatting, hope that is OK.
=> Fix the processing of org files with SRC blocks. Fixes #1065

liquid_tags/Readme.md
instructions were python2 only.
http://python-future.org/compatible_idioms.html#file-io-with-open
=> [liquid_tags] make docs python 2 and 3 compatible

yuicompressor/README.md, yuicompressor/yuicompressor.py
Changes:
1. Exit with error if the YUI Compressor command fails. No more silent errors.
2. Add a new setting - `YUICOMPRESSOR_EXECUTABLE` - to customize the expected name of the YUI Compressor executable.
3. Prevent problems with file names that have whitespace and shell metacharacters.
4. Remove useless verbosity option.
6. Edit README.md
Rationale for (2):
In the original readme, the suggested way of obtaining YUI Compressor is through pip. For YUI Compressor to work if it is installed using pip, the system must already have JRE installed (because YUI Compressor depends on JRE, and pip does not install JRE). For some people, this is not the best way to obtain YUI Compressor. Some people may already have YUI Compressor installed at a different path, or some may have already obtained YUI …
=> Fix the yuicompressor plugin

liquid_tags/graphviz.py
Python 2 did not require these import but Python 3 does.
=> liquid_tags: Python 3 requires from errno import EINVAL, EPIPE

bootstrap-rst/make-glyphicons.py, libravatar/test_libravatar.py
Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.
=> Use print() function in both Python 2 and Python 3

rmd_reader/rmd_reader.py
Upon upgrading to Pelican 4.0, I was presented with this error:
```
CRITICAL: TypeError: enabled() takes 0 positional arguments but 1 was given
```
pdb revealed this was when Pelican tried to access the `enabled` property of an `RmdReader` instance; since `enabled` was not declared to take `self`, the method doesn't work on instances. Adding the `self` argument now works perfectly.
=> Update rmd_reader to work in Pelican 4.0

plantuml/plantuml_rst.py
The plantuml Rst pluging was ignoring the `format` option in the `uml`
blocks, hardcoded to `png` all the time.  This did not allow for
generating `svg` images, as described in the Readme.rst.
Corrected the issue.
@mikitex70 and @mandaris and @justinmayer,
Please review.
=> plantuml: Fix reST format option

rmd_reader/rmd_reader.py
After the upgrade to pelican 4, I got warnings that told me to use {static} instead of {filename}. This change makes these warnings disappear as far as they were caused by my rmd articles.
=> rmd_reader: Avoid warning about the use of {filename}

better_figures_and_images/better_figures_and_images.py
This modification enables the better_figures_and_images plugin to accept the new {static} link syntax in place of the old {filename} which raises warnings when used with static content.
=> better_figures_and_images: Accept the new {static} link syntax

autopages/README.md
Related to #1083: explicitly state `author.page`, `category.page` and `tag.page` variables are `Page` objects and not "rendered content" in the `autopages` README. Rendered content could be intepreted as rendered HTML, not as page objects.
=> [autopages] Misleading variable descriptions in README

subcategory/subcategory.py
Currently using, for example, default category template on subcategory pages causes `CRITICAL: UndefinedError: 'articles_page' is undefined`
Due to getpelican/pelican#2384
=> subcategory: Fix pagination

render_math/math.py, render_math/mathjax_script_template
Changing `MATH_JAX[key] = value` was not affecting the final `MathJax.Config.Hub` output to the page, because the configuration script has to go _before_ the MathJax invocation, not after.
Also, it was not previously possible to force the use of TeX (or any of the other MathJax fonts) over STIX. I have fixed this, but it turned on equation numbering by default, so I have turned that off by default and made Pelican config variables for both things.
In `pelicanconf.py`, you can now specify
```python
MATH_JAX = {         'font_list': ['my_favorite_font', 'my_next_favorite'], 
'equation_numbering': 'none/auto/AMS'}
```
where fonts can be any of `TeX, STIX-Web, Asana-Math, Neo-Euler, Gyre-Pagella, Gyre-Termes, Latin-Modern`.
=> Render_Math: Fixed broken config script + Added variables for font & numbering

interlinks/interlinks.py
This occurs because Pelican now generates &gt; for >, so the old string replacement no longer works.
I tried to rebuild my site, but it failed, and upon investigation, it was because this string replace was failing.  &gt; did not need to be replaced with '>'
=> interlinks: Fix images not rendering

liquid_tags/Readme.md, liquid_tags/speakerdeck.py
Add an optional ratio for speakedeck viewer in Liquid tags plugin.
=> liquid_tags: Add optional ratio for Speakerdeck viewer

more_categories/README.md, more_categories/more_categories.py, more_categories/test_data/article_with_multiple_categories.rst, more_categories/test_more_categories.py
Fixes https://github.com/getpelican/pelican/issues/2565
The slug substitution settings changed in Pelican 4, and this wasn't yet reflected in this plugin. The plugin already only worked with Pelican >= 4, so backwards compatibility is not affected.
=> [more_categories] Fix category slug substitutions

filetime_from_git/git_wrapper.py
If your Pelican content is in a sub-directory then this plugin used to
fail. 
This patch fixes the issue.
=> filetime_from_git: enable searching parent directory

render_math/mathjax_script_template
I have opened an issue with MathJax for a rendering issue with render_math as a result of `preferredFont` and `availableFonts` not being set properly in MathJax.Hub.config["HTML-CSS"] section in `mathjax_script_template`. We were able to determine the following changes would fix the issue. Please see the below open issues.
https://github.com/mathjax/MathJax/issues/2148
https://github.com/getpelican/pelican-plugins/issues/1145
=> Fix MathJax availableFonts, prefferedFont rendering issue

extract_toc/extract_toc.py
In Markdown, if user adds `[TOC]` and the article does not
contain any headings, then `article.toc` ends up getting empty list.
```
<div><ul></ul></div>
```
This patch fixes this issue.
Related to https://github.com/Pelican-Elegant/elegant/issues/278
=> extract_toc: do not populate article.toc with empty list

i18n_subsites/localizing_using_jinja2.rst
The instructions about how to localize templates with Jinja2 are very confusing because if you follow the guide you would get the next error:
```
WARNING: JINJA_EXTENSIONS setting has been deprecated, moving it to JINJA_ENVIRONMENT setting.
CRITICAL: KeyError: 'JINJA_ENVIRONMENT'
```
For that I think it would be better to have it fixed and updated with the current system. The example codes are fine, they were replaced when it changed. If I am not wrong, it is the only file where this persists.
=> i18n_subsites: Replace JINJA_EXTENSIONS with JINJA_ENVIRONMENT in docs

neighbors/neighbors.py
Fixes #1160 
Tested with tests in #1184 which reproduced the bug.
**Problem description**: Relying on `StopIteration` exceptions bubbling out of generator functions is incorrect since Python 3.7, because these are transformed into `RuntimeError` exceptions. [More info on PEP 479](https://www.python.org/dev/peps/pep-0479/#explanation-of-generators-iterators-and-stopiteration).
=> [neighbors] Fix iter3() error on Python 3.7 and pass flake8

ctags_generator/README.md, ctags_generator/ctags_generator.py, ctags_generator/test_ctags_generator.py, w3c_validate/README.md, w3c_validate/test_content/getpelican.html, w3c_validate/test_wc3_validate.py, w3c_validate/wc3_validate.py
This plugin currently does not work with Python 3
This commit fixes that while staying fully backward-compatible.
It also adds a unit test for this plugin and fixes the one for the `ctags_generator` so that it will be invoked by Travis CI
=> Fix w3c_validate plugin for Python 3

liquid_tags/test_audio.py, liquid_tags/test_flickr.py, liquid_tags/test_generation.py, liquid_tags/test_giphy.py, liquid_tags/test_notebook.py, liquid_tags/test_soundcloud.py
Tested with:
```
$ nosetests --with-summary-report --summary-report-on=module-path liquid_tags
...
Summary:
module-path | success
----------------------------------
liquid_tags.test_generic |       1
----------------------------------------------------------------------
Ran 8 tests in 1.740s
OK (SKIP=7)
$ pytest liquid_tags
============================================== 28 passed, 3 skipped, 8 warnings in 4.33s ==============================================
```
=> Fixing liquid_tags plugin tests

ctags_generator/test_ctags_generator.py, more_categories/test_more_categories.py, neighbors/test_neighbors.py, render_math/test_render_math.py, shaarli_poster/shaarli_poster.py, shaarli_poster/test_shaarli_poster.py, sub_parts/test_sub_parts.py, tag_cloud/test_tag_cloud.py
Tested with:
```
nosetests ctags_generator
nosetests more_categories
nosetests neighbors
nosetests render_math
nosetests shaarli_poster
nosetests sub_parts
nosetests tag_cloud
```
=> Fix TypeError in tests: expected str, bytes or os.PathLike object, not NoneType

.travis.yml
This plugin reader caused urlescaping of curly braces,
which broke tests "test_filename_article_body" & "test_photo_article_body"
=> Fix photos plugin tests by excluding pandoc_reader

render_math/pelican_mathjax_markdown_extension.py
In issue #1212, inline math gets processed first, leaving $s in display math and rendering it incorrectly. Switching the priority order here makes it so that the double $$ for display math gets processed first.
=> Fix priority order for math processing (fixes #1212)

summary/Readme.rst, summary/requirements.txt, summary/summary.py, summary/test_summary.py
This resolves #1203, ensuring well-formed markup (the intent of #758).
=> Summary: Replace regex tag stripping with BeautifulSoup parsing

liquid_tags/Readme.md, liquid_tags/content/test_data/main.c, liquid_tags/content/test_data/main_cz.c, liquid_tags/include_code.py, liquid_tags/test_include_code.py
There is possibility to hide filename but there is no possibility to hide all elements (title + download link)
The following code:
```
{% include_code buffering/cat1.c lang:c :hideall: %}
```
Will produce something like this:
=> Add :hideall: tag for liquid_tags.include_code plugin

webring/README.md, webring/test_webring.py, webring/webring.py
After reading that [feedparser will remove its internal HTTP client in following releases](https://github.com/kurtmckee/feedparser/pull/178), it makes sense to stop using it.
This has the added benefit of removing the need to use a global unverified HTTPS context, which could be seen as a security risk.
The _Requests_ library was not used because the requirements were pretty simple and also to avoid another dependency.
=> Simplify Webring plugin HTTPS support

md_inline_extension/pelican_inline_markdown_extension.py
substitute basestring with str to work with python3 venv
=> md_inline_extension: Fix for Python 3 compatibility

Readme.rst, css-html-js-minify/__init__.py, css-html-js-minify/css_html_js_minify.py, css-html-js-minify/readme.rst
Hello,
This PR adds another plugin, pelican-cssmin, as a submodule.
It is essentially [this](https://github.com/zacharyvoase/cssmin), which is a Python-only port of the YUI css compressor. The key differences between the pre-existing yuicompressor plugin is that this version doesn't have the original compressor as a dependency and is fully contained with the relatively small plugin.
I figured I should add this to the pile in case others wanted to use it!
=> Add css-html-js-minify plugin

Readme.rst, shortcodes/README.md, shortcodes/__init__.py, shortcodes/shortcodes.py, shortcodes/test_shortcodes.py
This plugin allows to define macros called shortcodes in content pages that will be expanded as jinja2 templates.
The purpose of this plugin is to allow explicit and quick jinja2 templating in your content without compromising markdown/rst.
Example:
#pelicanconf.py
SHORTCODES = {
'image': "<img src=/images/{{src}}>{{desc|title}}<img>"
}
Then in your content:
[% image src=foo.png desc="this is a test" %]
will become:
=> Add Shortcodes plugin

liquid_tags/Readme.md, liquid_tags/include_code.py
A regression was introduced few patches ago, which placed code inside
the `figcaption` tag. This is not correct.
The original version has this layout
```
figure
figcaption
code
```
This patch fixes this issue. It also encloses metadata,
1. title
2. filename
3. line number
inside CSS classes. This let's themes improve the look of the
figcaption. Previously, all the metadata was piled into one `<span>`.
=> fix(liquid_tags.include_code): do not put code inside figcaption. Add CSS classes

asciidoc_reader/README.rst
If you omit the quotation when using the setting, the following error
occurs:
....
$ make devserver
CRITICAL: NameError: name 'asciidoc' is not defined
make: *** [Makefile:71: devserver] Fehler 1
....
=> Command description in readme must use quotation

liquid_tags/Readme.md, liquid_tags/test_youtube.py, liquid_tags/youtube.py
Adding <iframe> adds 1.2MB of javascript to webpage. And tracking
cookies.
Instead we can add thumbnail of video and link it to YouTube page. So
user can click to watch movie and is not tracked on our site.
YOUTUBE_THUMB_ONLY liquid config flag enables this mode
YOUTUBE_THUMB_SIZE allows to select one of YT thumbnails - there are
four of them defined:
- maxres: 1280x720
- sd:      640x360
- hq:      480x360
- mq:      320x180
'sd' one is used if not defined in LIQUID_CONFIGS variable.
=> liquid_tags/youtube: embed linked thumbnail

asciidoc_reader/asciidoc_reader.py
https://github.com/getpelican/pelican/issues/2694#issuecomment-621894352
> That said, I reviewed this thread and made what I surmised to be the relevant changes to the plugin via [getpelican/pelican-plugins@22831d1](https://github.com/getpelican/pelican-plugins/commit/22831d1da399ef54d732c395b0c6a28767622542), so hopefully that fixes the reported problem. If it doesn't, or I screwed it up and broke something horribly, [...]
Well, it does cause `NameError: name 'tempfile' is not defined`. :thinking: 
> [...] by all means please submit a PR in the repository where the plugins actually live. #YOLO
Here you go, @justinmayer :smiley:
=> Asciidoc: Fix "NameError: global name 'tempfile' is not defined"

optimize_images/optimize_images.py
Results in progressively-loaded JPEGs and smaller output file size.
=> optimize_images: Run jpegtran with -progressive switch

sitemap/sitemap.py
This fixes:
```
CRITICAL: NameError: name 'info' is not defined
Traceback (most recent call last):
File "/home/basti/PycharmProjects/venv/blog-py3/bin/pelican", line 10, in <module>
sys.exit(main())
File "/home/basti/PycharmProjects/venv/blog-py3/lib/python3.8/site-packages/pelican/__init__.py", line 570, in main
pelican.run()
File "/home/basti/PycharmProjects/venv/blog-py3/lib/python3.8/site-packages/pelican/__init__.py", line 137, in run
p.generate_output(writer)
File "/home/basti/PycharmProjects/blog/pelican-plugins/sitemap/sitemap.py", line 221, in generate_output
info('writing {0}'.format(path))
NameError: name 'info' is not defined
```
=> Sitemap: Fix info log message exception

Readme.rst
Changes:
* Add migration status of all plugins to keep track of progress.
* Add missing entries.
* Removes duplicate entries.
* Links to hosted plugin sub-folder.
* Links to external plugins (registered here by the way of git submodules).
* Links to migrated plugin repository.
* Re-order entries by their order of appearance in the repository.
I propose to add the following states symbols:
* (blank): Local hosted plugin is still waiting for migration work.
* ⚠️ : Deprecated. Can be safely removed from this repository.
* ❎: Externally maintained plugins that do not need explicit migration from the mono-repo. Migration work need to happen in the original owners' repo. Example: https://github.com/silentlamb/pelican-deadlinks/issues/8
* ✅: Repository has been migrated to …
=> Plugin inventory and migration status

related_posts/Readme.rst, thumbnailer/Readme.md
`related_posts` and `thumbnailer` plugins have been moved to their own repository. Add disclaimers in the same spirit as https://github.com/getpelican/pelican-plugins/pull/1289.
Relates to https://github.com/getpelican/pelican-plugins/issues/1290.
=> Add disclaimer for migrated plugins.

Readme.rst
Mark `multi_part` plugin has been [declared deprecated 6 years ago](https://github.com/getpelican/pelican-plugins/commit/62e09d3648b2d1ae516b932bd9f5f0477b654ac3).
=> multi_part plugin has been declared deprecated for a while.

Readme.rst
Similar Posts plugin is about to be release as an independent Python package for the first time, and can be flagged as migrated.
This PR depends on https://github.com/pelican-plugins/similar-posts/pull/5
=> Flag similar-posts plugin as migrated

Readme.rst
`image-process` plugin has just been moved to `pelican-plugins` organization and is about to be release as an independent Python package for the first time. It can be flagged as migrated.
See: https://github.com/pelican-plugins/image-process/issues/32#issuecomment-727580878
This closes #1227.
=> Flag image-process plugin as migrated

asciidoc_reader/asciidoc_reader.py
With this changes I can render Cyrillic posts with Cyrillic metadata via `asciidoctor` command.
Without this changes I get error:
```
UnicodeEncodeError: 'latin-1' codec can't encode characters
```
And non `ASCII` metadata not parsed.
I use `pelican 4.2.0`.
=> AsciiDoc Reader: Support Unicode Metadata

Readme.rst
`pandoc-reader` has plugin has been moved to its [own repository](https://github.com/pelican-plugins/pandoc-reader).
Relates to: 
* #1303
* https://github.com/pelican-plugins/pandoc-reader/issues/1
=> [Migration] Flag pandoc-reader as migrated

gzip_cache/Readme.rst, gzip_cache/gzip_cache.py, gzip_cache/test_gzip_cache.py
=> Add user-facing GZIP_CACHE_EXCLUDE_TYPES file type exclusion list

rmd_reader/rmd_reader.py
Fixes #1132.
rpy2 changed its API for 3.0, and moved `set_initoptions()` from `rpy2.rinterface` to `rpy2.rinterface_lib.embedded`. It also changed the argument from a tuple of bytes to a tuple of strings. This PR tries to run it as rpy2 v2, and if the method lookup fails, it tries the rpy2 v3 setup. I've tested this with both rpy2==3.0.2 and rpy2==2.9.5.
=> rmd_reader: Make set_initoptions() compatible with rpy2 v3

Readme.rst, liquid_tags/Readme.md
Depends on https://github.com/pelican-plugins/liquid-tags/issues/1
=> [Migration] Flag Liquid Tags plugin as migrated

thumbnailer/Readme.md
Fix a mistake I made copy/pasting reStructuredText disclaimer content to a Markdown file.
=> [Migration] Fix Markdown migration disclaimer

org_reader/org_reader.el
`org-file-properties` is deprecated since Org-Mode 9.3[1]
[1] https://github.com/bzg/org-mode/commit/1bdff9f73dc1e7ff625a90e3e61350bdea99f29c
=> [org_reader] Replace obsolete variables

Readme.rst
The plugin description table wasn't showing up. Added one space before the description on every line to fix this.
=> Fix plugin descriptions table

pelican_comment_system/pelican_comment_system.py
This pull request fix the following error with the `pelican_comment_system` plugin:
```
CRITICAL: 'Pelican' object has no attribute 'get_writer'
```
Since https://github.com/getpelican/pelican/pull/2821 `get_writer()` is renamed `_get_writer()`, this pull request only rename this function call.
=> [pelican_comment_system] Fix _get_writer() call

Readme.rst, photos/README.md
After #1342 has been finished this marks the photos plugin as migrated.
=> Mark photos plugin as migrated

asciidoc_reader/asciidoc_reader.py
Currently, the metadata parsing regex look like this:
```py
regexp = re.compile(r"^:[A-z]+:\s*\w")
```
The `\w` part is quite restrictive on allowed values. For example, if I start a metadata value with a period, the metadata will be ignored (which is how I discovered this). I don't see any good reason to make it restrictive at all - why care what characters people want to put in the metadata value?
This regex just accepts whatever until the end of the line:
```py
regexp = re.compile(r"^:[A-z]+:\s*.*$")
```
Given that this isn't capturing anything, just matching, why not simplify even further:
```py
regexp = re.compile(r"^:\w+:")
```
=> [asciidoc-reader] Make metadata parsing regex less restrictive

plantuml/plantuml_rst.py
The code for pelican >= 3.7.0 passes an empty dict instead passing the actual
config dict.
Closes #1142
=> plantuml: fix empty SITEURL

events/events.py, events/events_list.html
… instead of just lightweight Event()-objects. This enables the template to place links to the real article url. Pages therefore do not need to have a slug header anymore for these links to work.
=> [events] fixed: populate events-list template variable with the Article() objects

asciidoc_reader/asciidoc_reader.py
We process the content twice, once on line 63, then again on 67 - just keep the last one.
=> asciidoc_reader: Don't process content twice

bootstrap-rst/bootstrap.py
bootstrap-rst was crashing with recent docutils, issue was the handling of math_header which caused an excpetion in `docutils/writers/_html_base.py`:
```
", line 167, in interpolation_dict
subs[attr] = ''.join(getattr(self,
attr)).rstrip('\n')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 2: expected str instance,
list found
```
=> `bootstrap-rst`: Math header is an array, so should be joined not appended

asciidoc_reader/asciidoc_reader.py, asciidoc_reader/test_asciidoc_reader.py, asciidoc_reader/test_data/article_with_asc_multiline.asc
According to the Asciidoctor reference [1], multiline attributes are supported by ending the previous line with a backslash. This can be useful for long attributes, such as the description, and it matches what you can already do with reStructuredText.
[1]: https://docs.asciidoctor.org/asciidoc/latest/attributes/wrap-values/
=> asciidoc-reader: support multiline AsciiDoc attributes

Readme.rst
Clarify `code_include` (it is not just for RST-format, but also for Markdown-format, files
=> Clarify `Code Include` plugin scope in README

asciidoc_reader/asciidoc_reader.py
`shutil.which` is a standard and multiplatform solution to perform checks like this.
This solves the issue described in #1401.
=> [asciidoc_reader] use `shutil.which` to detect available binaries

representative_image/representative_image.py
I have a few hidden pages on a my website, and I could not figure why the representative image was incorrect.
This very short PR simply aims to generate representative images for ALL kind of articles & pages.
I tested it on my own blog, and it works fine.
=> [representative_image] Also process draft & hidden articles & pages
